// Code generated by mockery. DO NOT EDIT.

package filesystem

import (
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// mockOsReadsProvider is an autogenerated mock type for the osReadsProvider type
type mockOsReadsProvider struct {
	mock.Mock
}

type mockOsReadsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOsReadsProvider) EXPECT() *mockOsReadsProvider_Expecter {
	return &mockOsReadsProvider_Expecter{mock: &_m.Mock}
}

// ReadDir provides a mock function with given fields: name
func (_m *mockOsReadsProvider) ReadDir(name string) ([]os.DirEntry, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []os.DirEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]os.DirEntry, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []os.DirEntry); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]os.DirEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockOsReadsProvider_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type mockOsReadsProvider_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - name string
func (_e *mockOsReadsProvider_Expecter) ReadDir(name interface{}) *mockOsReadsProvider_ReadDir_Call {
	return &mockOsReadsProvider_ReadDir_Call{Call: _e.mock.On("ReadDir", name)}
}

func (_c *mockOsReadsProvider_ReadDir_Call) Run(run func(name string)) *mockOsReadsProvider_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockOsReadsProvider_ReadDir_Call) Return(_a0 []os.DirEntry, _a1 error) *mockOsReadsProvider_ReadDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockOsReadsProvider_ReadDir_Call) RunAndReturn(run func(string) ([]os.DirEntry, error)) *mockOsReadsProvider_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// Readlink provides a mock function with given fields: name
func (_m *mockOsReadsProvider) Readlink(name string) (string, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Readlink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockOsReadsProvider_Readlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Readlink'
type mockOsReadsProvider_Readlink_Call struct {
	*mock.Call
}

// Readlink is a helper method to define mock.On call
//   - name string
func (_e *mockOsReadsProvider_Expecter) Readlink(name interface{}) *mockOsReadsProvider_Readlink_Call {
	return &mockOsReadsProvider_Readlink_Call{Call: _e.mock.On("Readlink", name)}
}

func (_c *mockOsReadsProvider_Readlink_Call) Run(run func(name string)) *mockOsReadsProvider_Readlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockOsReadsProvider_Readlink_Call) Return(_a0 string, _a1 error) *mockOsReadsProvider_Readlink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockOsReadsProvider_Readlink_Call) RunAndReturn(run func(string) (string, error)) *mockOsReadsProvider_Readlink_Call {
	_c.Call.Return(run)
	return _c
}

// newMockOsReadsProvider creates a new instance of mockOsReadsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOsReadsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOsReadsProvider {
	mock := &mockOsReadsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
