// Code generated by mockery. DO NOT EDIT.

package filesystem

import (
	mock "github.com/stretchr/testify/mock"
	unix "golang.org/x/sys/unix"
)

// mockUnixStatfsProvider is an autogenerated mock type for the unixStatfsProvider type
type mockUnixStatfsProvider struct {
	mock.Mock
}

type mockUnixStatfsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockUnixStatfsProvider) EXPECT() *mockUnixStatfsProvider_Expecter {
	return &mockUnixStatfsProvider_Expecter{mock: &_m.Mock}
}

// Statfs provides a mock function with given fields: path, buf
func (_m *mockUnixStatfsProvider) Statfs(path string, buf *unix.Statfs_t) error {
	ret := _m.Called(path, buf)

	if len(ret) == 0 {
		panic("no return value specified for Statfs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *unix.Statfs_t) error); ok {
		r0 = rf(path, buf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockUnixStatfsProvider_Statfs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Statfs'
type mockUnixStatfsProvider_Statfs_Call struct {
	*mock.Call
}

// Statfs is a helper method to define mock.On call
//   - path string
//   - buf *unix.Statfs_t
func (_e *mockUnixStatfsProvider_Expecter) Statfs(path interface{}, buf interface{}) *mockUnixStatfsProvider_Statfs_Call {
	return &mockUnixStatfsProvider_Statfs_Call{Call: _e.mock.On("Statfs", path, buf)}
}

func (_c *mockUnixStatfsProvider_Statfs_Call) Run(run func(path string, buf *unix.Statfs_t)) *mockUnixStatfsProvider_Statfs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*unix.Statfs_t))
	})
	return _c
}

func (_c *mockUnixStatfsProvider_Statfs_Call) Return(_a0 error) *mockUnixStatfsProvider_Statfs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockUnixStatfsProvider_Statfs_Call) RunAndReturn(run func(string, *unix.Statfs_t) error) *mockUnixStatfsProvider_Statfs_Call {
	_c.Call.Return(run)
	return _c
}

// newMockUnixStatfsProvider creates a new instance of mockUnixStatfsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUnixStatfsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUnixStatfsProvider {
	mock := &mockUnixStatfsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
