// Code generated by mockery. DO NOT EDIT.

package filesystem

import (
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// mockOsProvider is an autogenerated mock type for the osProvider type
type mockOsProvider struct {
	mock.Mock
}

type mockOsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOsProvider) EXPECT() *mockOsProvider_Expecter {
	return &mockOsProvider_Expecter{mock: &_m.Mock}
}

// Open provides a mock function with given fields: name
func (_m *mockOsProvider) Open(name string) (*os.File, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 *os.File
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*os.File, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockOsProvider_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type mockOsProvider_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *mockOsProvider_Expecter) Open(name interface{}) *mockOsProvider_Open_Call {
	return &mockOsProvider_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *mockOsProvider_Open_Call) Run(run func(name string)) *mockOsProvider_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockOsProvider_Open_Call) Return(_a0 *os.File, _a1 error) *mockOsProvider_Open_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockOsProvider_Open_Call) RunAndReturn(run func(string) (*os.File, error)) *mockOsProvider_Open_Call {
	_c.Call.Return(run)
	return _c
}

// OpenFile provides a mock function with given fields: name, flag, perm
func (_m *mockOsProvider) OpenFile(name string, flag int, perm os.FileMode) (*os.File, error) {
	ret := _m.Called(name, flag, perm)

	if len(ret) == 0 {
		panic("no return value specified for OpenFile")
	}

	var r0 *os.File
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, os.FileMode) (*os.File, error)); ok {
		return rf(name, flag, perm)
	}
	if rf, ok := ret.Get(0).(func(string, int, os.FileMode) *os.File); ok {
		r0 = rf(name, flag, perm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, os.FileMode) error); ok {
		r1 = rf(name, flag, perm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockOsProvider_OpenFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenFile'
type mockOsProvider_OpenFile_Call struct {
	*mock.Call
}

// OpenFile is a helper method to define mock.On call
//   - name string
//   - flag int
//   - perm os.FileMode
func (_e *mockOsProvider_Expecter) OpenFile(name interface{}, flag interface{}, perm interface{}) *mockOsProvider_OpenFile_Call {
	return &mockOsProvider_OpenFile_Call{Call: _e.mock.On("OpenFile", name, flag, perm)}
}

func (_c *mockOsProvider_OpenFile_Call) Run(run func(name string, flag int, perm os.FileMode)) *mockOsProvider_OpenFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int), args[2].(os.FileMode))
	})
	return _c
}

func (_c *mockOsProvider_OpenFile_Call) Return(_a0 *os.File, _a1 error) *mockOsProvider_OpenFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockOsProvider_OpenFile_Call) RunAndReturn(run func(string, int, os.FileMode) (*os.File, error)) *mockOsProvider_OpenFile_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function with given fields: name
func (_m *mockOsProvider) ReadDir(name string) ([]os.DirEntry, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []os.DirEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]os.DirEntry, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []os.DirEntry); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]os.DirEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockOsProvider_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type mockOsProvider_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - name string
func (_e *mockOsProvider_Expecter) ReadDir(name interface{}) *mockOsProvider_ReadDir_Call {
	return &mockOsProvider_ReadDir_Call{Call: _e.mock.On("ReadDir", name)}
}

func (_c *mockOsProvider_ReadDir_Call) Run(run func(name string)) *mockOsProvider_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockOsProvider_ReadDir_Call) Return(_a0 []os.DirEntry, _a1 error) *mockOsProvider_ReadDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockOsProvider_ReadDir_Call) RunAndReturn(run func(string) ([]os.DirEntry, error)) *mockOsProvider_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// Readlink provides a mock function with given fields: name
func (_m *mockOsProvider) Readlink(name string) (string, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Readlink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockOsProvider_Readlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Readlink'
type mockOsProvider_Readlink_Call struct {
	*mock.Call
}

// Readlink is a helper method to define mock.On call
//   - name string
func (_e *mockOsProvider_Expecter) Readlink(name interface{}) *mockOsProvider_Readlink_Call {
	return &mockOsProvider_Readlink_Call{Call: _e.mock.On("Readlink", name)}
}

func (_c *mockOsProvider_Readlink_Call) Run(run func(name string)) *mockOsProvider_Readlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockOsProvider_Readlink_Call) Return(_a0 string, _a1 error) *mockOsProvider_Readlink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockOsProvider_Readlink_Call) RunAndReturn(run func(string) (string, error)) *mockOsProvider_Readlink_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: name
func (_m *mockOsProvider) Remove(name string) error {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockOsProvider_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type mockOsProvider_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - name string
func (_e *mockOsProvider_Expecter) Remove(name interface{}) *mockOsProvider_Remove_Call {
	return &mockOsProvider_Remove_Call{Call: _e.mock.On("Remove", name)}
}

func (_c *mockOsProvider_Remove_Call) Run(run func(name string)) *mockOsProvider_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockOsProvider_Remove_Call) Return(_a0 error) *mockOsProvider_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOsProvider_Remove_Call) RunAndReturn(run func(string) error) *mockOsProvider_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function with given fields: oldpath, newpath
func (_m *mockOsProvider) Rename(oldpath string, newpath string) error {
	ret := _m.Called(oldpath, newpath)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(oldpath, newpath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockOsProvider_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type mockOsProvider_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - oldpath string
//   - newpath string
func (_e *mockOsProvider_Expecter) Rename(oldpath interface{}, newpath interface{}) *mockOsProvider_Rename_Call {
	return &mockOsProvider_Rename_Call{Call: _e.mock.On("Rename", oldpath, newpath)}
}

func (_c *mockOsProvider_Rename_Call) Run(run func(oldpath string, newpath string)) *mockOsProvider_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *mockOsProvider_Rename_Call) Return(_a0 error) *mockOsProvider_Rename_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOsProvider_Rename_Call) RunAndReturn(run func(string, string) error) *mockOsProvider_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function with given fields: name
func (_m *mockOsProvider) Stat(name string) (os.FileInfo, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 os.FileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockOsProvider_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type mockOsProvider_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *mockOsProvider_Expecter) Stat(name interface{}) *mockOsProvider_Stat_Call {
	return &mockOsProvider_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *mockOsProvider_Stat_Call) Run(run func(name string)) *mockOsProvider_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockOsProvider_Stat_Call) Return(_a0 os.FileInfo, _a1 error) *mockOsProvider_Stat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockOsProvider_Stat_Call) RunAndReturn(run func(string) (os.FileInfo, error)) *mockOsProvider_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// newMockOsProvider creates a new instance of mockOsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOsProvider {
	mock := &mockOsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
