// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	filesystem "github.com/desertwitch/gover/internal/generic/filesystem"
	mock "github.com/stretchr/testify/mock"

	schema "github.com/desertwitch/gover/internal/generic/schema"
)

// DiskStatProvider is an autogenerated mock type for the diskStatProvider type
type DiskStatProvider struct {
	mock.Mock
}

type DiskStatProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *DiskStatProvider) EXPECT() *DiskStatProvider_Expecter {
	return &DiskStatProvider_Expecter{mock: &_m.Mock}
}

// GetDiskUsage provides a mock function with given fields: storage
func (_m *DiskStatProvider) GetDiskUsage(storage schema.Storage) (filesystem.DiskStats, error) {
	ret := _m.Called(storage)

	if len(ret) == 0 {
		panic("no return value specified for GetDiskUsage")
	}

	var r0 filesystem.DiskStats
	var r1 error
	if rf, ok := ret.Get(0).(func(schema.Storage) (filesystem.DiskStats, error)); ok {
		return rf(storage)
	}
	if rf, ok := ret.Get(0).(func(schema.Storage) filesystem.DiskStats); ok {
		r0 = rf(storage)
	} else {
		r0 = ret.Get(0).(filesystem.DiskStats)
	}

	if rf, ok := ret.Get(1).(func(schema.Storage) error); ok {
		r1 = rf(storage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DiskStatProvider_GetDiskUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDiskUsage'
type DiskStatProvider_GetDiskUsage_Call struct {
	*mock.Call
}

// GetDiskUsage is a helper method to define mock.On call
//   - storage schema.Storage
func (_e *DiskStatProvider_Expecter) GetDiskUsage(storage interface{}) *DiskStatProvider_GetDiskUsage_Call {
	return &DiskStatProvider_GetDiskUsage_Call{Call: _e.mock.On("GetDiskUsage", storage)}
}

func (_c *DiskStatProvider_GetDiskUsage_Call) Run(run func(storage schema.Storage)) *DiskStatProvider_GetDiskUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(schema.Storage))
	})
	return _c
}

func (_c *DiskStatProvider_GetDiskUsage_Call) Return(_a0 filesystem.DiskStats, _a1 error) *DiskStatProvider_GetDiskUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DiskStatProvider_GetDiskUsage_Call) RunAndReturn(run func(schema.Storage) (filesystem.DiskStats, error)) *DiskStatProvider_GetDiskUsage_Call {
	_c.Call.Return(run)
	return _c
}

// HasEnoughFreeSpace provides a mock function with given fields: s, minFree, fileSize
func (_m *DiskStatProvider) HasEnoughFreeSpace(s schema.Storage, minFree uint64, fileSize uint64) (bool, error) {
	ret := _m.Called(s, minFree, fileSize)

	if len(ret) == 0 {
		panic("no return value specified for HasEnoughFreeSpace")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(schema.Storage, uint64, uint64) (bool, error)); ok {
		return rf(s, minFree, fileSize)
	}
	if rf, ok := ret.Get(0).(func(schema.Storage, uint64, uint64) bool); ok {
		r0 = rf(s, minFree, fileSize)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(schema.Storage, uint64, uint64) error); ok {
		r1 = rf(s, minFree, fileSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DiskStatProvider_HasEnoughFreeSpace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasEnoughFreeSpace'
type DiskStatProvider_HasEnoughFreeSpace_Call struct {
	*mock.Call
}

// HasEnoughFreeSpace is a helper method to define mock.On call
//   - s schema.Storage
//   - minFree uint64
//   - fileSize uint64
func (_e *DiskStatProvider_Expecter) HasEnoughFreeSpace(s interface{}, minFree interface{}, fileSize interface{}) *DiskStatProvider_HasEnoughFreeSpace_Call {
	return &DiskStatProvider_HasEnoughFreeSpace_Call{Call: _e.mock.On("HasEnoughFreeSpace", s, minFree, fileSize)}
}

func (_c *DiskStatProvider_HasEnoughFreeSpace_Call) Run(run func(s schema.Storage, minFree uint64, fileSize uint64)) *DiskStatProvider_HasEnoughFreeSpace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(schema.Storage), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *DiskStatProvider_HasEnoughFreeSpace_Call) Return(_a0 bool, _a1 error) *DiskStatProvider_HasEnoughFreeSpace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DiskStatProvider_HasEnoughFreeSpace_Call) RunAndReturn(run func(schema.Storage, uint64, uint64) (bool, error)) *DiskStatProvider_HasEnoughFreeSpace_Call {
	_c.Call.Return(run)
	return _c
}

// NewDiskStatProvider creates a new instance of DiskStatProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiskStatProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiskStatProvider {
	mock := &DiskStatProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
