// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// FsWalkProvider is an autogenerated mock type for the fsWalkProvider type
type FsWalkProvider struct {
	mock.Mock
}

type FsWalkProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *FsWalkProvider) EXPECT() *FsWalkProvider_Expecter {
	return &FsWalkProvider_Expecter{mock: &_m.Mock}
}

// WalkDir provides a mock function with given fields: root, fn
func (_m *FsWalkProvider) WalkDir(root string, fn fs.WalkDirFunc) error {
	ret := _m.Called(root, fn)

	if len(ret) == 0 {
		panic("no return value specified for WalkDir")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, fs.WalkDirFunc) error); ok {
		r0 = rf(root, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FsWalkProvider_WalkDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WalkDir'
type FsWalkProvider_WalkDir_Call struct {
	*mock.Call
}

// WalkDir is a helper method to define mock.On call
//   - root string
//   - fn fs.WalkDirFunc
func (_e *FsWalkProvider_Expecter) WalkDir(root interface{}, fn interface{}) *FsWalkProvider_WalkDir_Call {
	return &FsWalkProvider_WalkDir_Call{Call: _e.mock.On("WalkDir", root, fn)}
}

func (_c *FsWalkProvider_WalkDir_Call) Run(run func(root string, fn fs.WalkDirFunc)) *FsWalkProvider_WalkDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(fs.WalkDirFunc))
	})
	return _c
}

func (_c *FsWalkProvider_WalkDir_Call) Return(_a0 error) *FsWalkProvider_WalkDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FsWalkProvider_WalkDir_Call) RunAndReturn(run func(string, fs.WalkDirFunc) error) *FsWalkProvider_WalkDir_Call {
	_c.Call.Return(run)
	return _c
}

// NewFsWalkProvider creates a new instance of FsWalkProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFsWalkProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *FsWalkProvider {
	mock := &FsWalkProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
