// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InUseProvider is an autogenerated mock type for the inUseProvider type
type InUseProvider struct {
	mock.Mock
}

type InUseProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *InUseProvider) EXPECT() *InUseProvider_Expecter {
	return &InUseProvider_Expecter{mock: &_m.Mock}
}

// IsInUse provides a mock function with given fields: path
func (_m *InUseProvider) IsInUse(path string) bool {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for IsInUse")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// InUseProvider_IsInUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInUse'
type InUseProvider_IsInUse_Call struct {
	*mock.Call
}

// IsInUse is a helper method to define mock.On call
//   - path string
func (_e *InUseProvider_Expecter) IsInUse(path interface{}) *InUseProvider_IsInUse_Call {
	return &InUseProvider_IsInUse_Call{Call: _e.mock.On("IsInUse", path)}
}

func (_c *InUseProvider_IsInUse_Call) Run(run func(path string)) *InUseProvider_IsInUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *InUseProvider_IsInUse_Call) Return(_a0 bool) *InUseProvider_IsInUse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InUseProvider_IsInUse_Call) RunAndReturn(run func(string) bool) *InUseProvider_IsInUse_Call {
	_c.Call.Return(run)
	return _c
}

// NewInUseProvider creates a new instance of InUseProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInUseProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *InUseProvider {
	mock := &InUseProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
