// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// GetFSPath provides a mock function with no fields
func (_m *Storage) GetFSPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFSPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Storage_GetFSPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFSPath'
type Storage_GetFSPath_Call struct {
	*mock.Call
}

// GetFSPath is a helper method to define mock.On call
func (_e *Storage_Expecter) GetFSPath() *Storage_GetFSPath_Call {
	return &Storage_GetFSPath_Call{Call: _e.mock.On("GetFSPath")}
}

func (_c *Storage_GetFSPath_Call) Run(run func()) *Storage_GetFSPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Storage_GetFSPath_Call) Return(_a0 string) *Storage_GetFSPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_GetFSPath_Call) RunAndReturn(run func() string) *Storage_GetFSPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with no fields
func (_m *Storage) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Storage_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type Storage_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *Storage_Expecter) GetName() *Storage_GetName_Call {
	return &Storage_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *Storage_GetName_Call) Run(run func()) *Storage_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Storage_GetName_Call) Return(_a0 string) *Storage_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_GetName_Call) RunAndReturn(run func() string) *Storage_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
