linters:
    enable-all: true
    disable:
            - cyclop
            - depguard
            - dupl
            - exhaustruct
            - funlen
            - gocognit
            - gocyclo
            - lll
            - nestif
            - tenv
            - varnamelen
            - wrapcheck
            - wsl
issues:
    exclude-rules:
        - path: ".*\\.go"
          text: "result 0 \\(error\\) is always nil"
