linters:
    # Enable all available linters.
    # Default: false
    enable-all: true
    # Disable specific linter
    # https://golangci-lint.run/usage/linters/#disabled-by-default
    disable:
            - wsl
            - lll
            - dupl
            - wrapcheck
            - varnamelen
            - depguard
            - exhaustruct
issues:
    exclude-rules:
        - path: ".*\\.go"
          text: "(error) is always nil"
