linters:
    enable-all: true
    disable:
            - wsl
            - lll
            - funlen
            - dupl
            - wrapcheck
            - varnamelen
            - depguard
            - exhaustruct
            - gocognit
            - gocyclo
            - cyclop
            - nestif
issues:
    exclude-rules:
        - path: ".*\\.go"
          text: "result 0 \\(error\\) is always nil"
