version: "2"
linters:
  default: all
  disable:
    - depguard
    - dupl
    - exhaustruct
    - gochecknoglobals
    - goconst
    - noinlineerr
    - testpackage
    - varnamelen
    - wsl
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 20
      package-average: 20
    funlen:
      lines: 80
      statements: 50
      ignore-comments: true
    gocognit:
      min-complexity: 40
    gomoddirectives:
      replace-allow-list:
        - github.com/charmbracelet/bubbletea
    lll:
      line-length: 180
    nestif:
      min-complexity: 6
    paralleltest:
      ignore-missing-subtests: true
    staticcheck:
      checks:
        - all
        - -S1008
        - -QF1008
    wrapcheck:
      ignore-sig-regexps:
        - unix.*?\(
        - os.*?\(
        - filepath.*?\(
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - err113
          - funlen
          - ireturn
          - revive
          - tparallel
        path: _test\.go
      - linters:
          - revive
        text: "Go standard library package names"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
