all: true
dir: '{{.InterfaceDirRelative}}'
structname: '{{.Mock}}_{{.InterfaceName}}'
recursive: true
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/desertwitch/gover/internal: {}
