with-expecter: true
dry-run: false
mockname: "{{.InterfaceName | firstUpper | camelcase}}"
filename: "{{.InterfaceName}}.go"
dir: "{{.InterfaceDirRelative}}/mocks"
outpkg: "mocks"
recursive: true
all: true
exported: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: True
packages:
  github.com/desertwitch/gover/internal:

