// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	filesystem "github.com/desertwitch/gover/internal/filesystem"
	mock "github.com/stretchr/testify/mock"
)

// ArrayType is an autogenerated mock type for the ArrayType type
type ArrayType struct {
	mock.Mock
}

type ArrayType_Expecter struct {
	mock *mock.Mock
}

func (_m *ArrayType) EXPECT() *ArrayType_Expecter {
	return &ArrayType_Expecter{mock: &_m.Mock}
}

// GetDisks provides a mock function with no fields
func (_m *ArrayType) GetDisks() map[string]filesystem.DiskType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDisks")
	}

	var r0 map[string]filesystem.DiskType
	if rf, ok := ret.Get(0).(func() map[string]filesystem.DiskType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]filesystem.DiskType)
		}
	}

	return r0
}

// ArrayType_GetDisks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDisks'
type ArrayType_GetDisks_Call struct {
	*mock.Call
}

// GetDisks is a helper method to define mock.On call
func (_e *ArrayType_Expecter) GetDisks() *ArrayType_GetDisks_Call {
	return &ArrayType_GetDisks_Call{Call: _e.mock.On("GetDisks")}
}

func (_c *ArrayType_GetDisks_Call) Run(run func()) *ArrayType_GetDisks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ArrayType_GetDisks_Call) Return(_a0 map[string]filesystem.DiskType) *ArrayType_GetDisks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArrayType_GetDisks_Call) RunAndReturn(run func() map[string]filesystem.DiskType) *ArrayType_GetDisks_Call {
	_c.Call.Return(run)
	return _c
}

// NewArrayType creates a new instance of ArrayType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArrayType(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArrayType {
	mock := &ArrayType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
