// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	filesystem "github.com/desertwitch/gover/internal/filesystem"
	mock "github.com/stretchr/testify/mock"
)

// RelatedElement is an autogenerated mock type for the relatedElement type
type RelatedElement struct {
	mock.Mock
}

type RelatedElement_Expecter struct {
	mock *mock.Mock
}

func (_m *RelatedElement) EXPECT() *RelatedElement_Expecter {
	return &RelatedElement_Expecter{mock: &_m.Mock}
}

// GetDestPath provides a mock function with no fields
func (_m *RelatedElement) GetDestPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDestPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RelatedElement_GetDestPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDestPath'
type RelatedElement_GetDestPath_Call struct {
	*mock.Call
}

// GetDestPath is a helper method to define mock.On call
func (_e *RelatedElement_Expecter) GetDestPath() *RelatedElement_GetDestPath_Call {
	return &RelatedElement_GetDestPath_Call{Call: _e.mock.On("GetDestPath")}
}

func (_c *RelatedElement_GetDestPath_Call) Run(run func()) *RelatedElement_GetDestPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RelatedElement_GetDestPath_Call) Return(_a0 string) *RelatedElement_GetDestPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelatedElement_GetDestPath_Call) RunAndReturn(run func() string) *RelatedElement_GetDestPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadata provides a mock function with no fields
func (_m *RelatedElement) GetMetadata() *filesystem.Metadata {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 *filesystem.Metadata
	if rf, ok := ret.Get(0).(func() *filesystem.Metadata); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*filesystem.Metadata)
		}
	}

	return r0
}

// RelatedElement_GetMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadata'
type RelatedElement_GetMetadata_Call struct {
	*mock.Call
}

// GetMetadata is a helper method to define mock.On call
func (_e *RelatedElement_Expecter) GetMetadata() *RelatedElement_GetMetadata_Call {
	return &RelatedElement_GetMetadata_Call{Call: _e.mock.On("GetMetadata")}
}

func (_c *RelatedElement_GetMetadata_Call) Run(run func()) *RelatedElement_GetMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RelatedElement_GetMetadata_Call) Return(_a0 *filesystem.Metadata) *RelatedElement_GetMetadata_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelatedElement_GetMetadata_Call) RunAndReturn(run func() *filesystem.Metadata) *RelatedElement_GetMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetSourcePath provides a mock function with no fields
func (_m *RelatedElement) GetSourcePath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSourcePath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RelatedElement_GetSourcePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSourcePath'
type RelatedElement_GetSourcePath_Call struct {
	*mock.Call
}

// GetSourcePath is a helper method to define mock.On call
func (_e *RelatedElement_Expecter) GetSourcePath() *RelatedElement_GetSourcePath_Call {
	return &RelatedElement_GetSourcePath_Call{Call: _e.mock.On("GetSourcePath")}
}

func (_c *RelatedElement_GetSourcePath_Call) Run(run func()) *RelatedElement_GetSourcePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RelatedElement_GetSourcePath_Call) Return(_a0 string) *RelatedElement_GetSourcePath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RelatedElement_GetSourcePath_Call) RunAndReturn(run func() string) *RelatedElement_GetSourcePath_Call {
	_c.Call.Return(run)
	return _c
}

// NewRelatedElement creates a new instance of RelatedElement. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRelatedElement(t interface {
	mock.TestingT
	Cleanup(func())
}) *RelatedElement {
	mock := &RelatedElement{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
