// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StorageType is an autogenerated mock type for the StorageType type
type StorageType struct {
	mock.Mock
}

type StorageType_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageType) EXPECT() *StorageType_Expecter {
	return &StorageType_Expecter{mock: &_m.Mock}
}

// GetFSPath provides a mock function with no fields
func (_m *StorageType) GetFSPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFSPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// StorageType_GetFSPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFSPath'
type StorageType_GetFSPath_Call struct {
	*mock.Call
}

// GetFSPath is a helper method to define mock.On call
func (_e *StorageType_Expecter) GetFSPath() *StorageType_GetFSPath_Call {
	return &StorageType_GetFSPath_Call{Call: _e.mock.On("GetFSPath")}
}

func (_c *StorageType_GetFSPath_Call) Run(run func()) *StorageType_GetFSPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StorageType_GetFSPath_Call) Return(_a0 string) *StorageType_GetFSPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageType_GetFSPath_Call) RunAndReturn(run func() string) *StorageType_GetFSPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with no fields
func (_m *StorageType) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// StorageType_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type StorageType_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *StorageType_Expecter) GetName() *StorageType_GetName_Call {
	return &StorageType_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *StorageType_GetName_Call) Run(run func()) *StorageType_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StorageType_GetName_Call) Return(_a0 string) *StorageType_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageType_GetName_Call) RunAndReturn(run func() string) *StorageType_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageType creates a new instance of StorageType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageType(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageType {
	mock := &StorageType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
