// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package configuration

import (
	mock "github.com/stretchr/testify/mock"
)

// newMock_genericConfigProvider creates a new instance of mock_genericConfigProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMock_genericConfigProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mock_genericConfigProvider {
	mock := &mock_genericConfigProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mock_genericConfigProvider is an autogenerated mock type for the genericConfigProvider type
type mock_genericConfigProvider struct {
	mock.Mock
}

type mock_genericConfigProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mock_genericConfigProvider) EXPECT() *mock_genericConfigProvider_Expecter {
	return &mock_genericConfigProvider_Expecter{mock: &_m.Mock}
}

// Read provides a mock function for the type mock_genericConfigProvider
func (_mock *mock_genericConfigProvider) Read(filenames ...string) (map[string]string, error) {
	// string
	_va := make([]interface{}, len(filenames))
	for _i := range filenames {
		_va[_i] = filenames[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...string) (map[string]string, error)); ok {
		return returnFunc(filenames...)
	}
	if returnFunc, ok := ret.Get(0).(func(...string) map[string]string); ok {
		r0 = returnFunc(filenames...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...string) error); ok {
		r1 = returnFunc(filenames...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mock_genericConfigProvider_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type mock_genericConfigProvider_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - filenames ...string
func (_e *mock_genericConfigProvider_Expecter) Read(filenames ...interface{}) *mock_genericConfigProvider_Read_Call {
	return &mock_genericConfigProvider_Read_Call{Call: _e.mock.On("Read",
		append([]interface{}{}, filenames...)...)}
}

func (_c *mock_genericConfigProvider_Read_Call) Run(run func(filenames ...string)) *mock_genericConfigProvider_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *mock_genericConfigProvider_Read_Call) Return(envMap map[string]string, err error) *mock_genericConfigProvider_Read_Call {
	_c.Call.Return(envMap, err)
	return _c
}

func (_c *mock_genericConfigProvider_Read_Call) RunAndReturn(run func(filenames ...string) (map[string]string, error)) *mock_genericConfigProvider_Read_Call {
	_c.Call.Return(run)
	return _c
}
