// Code generated by mockery v2.52.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnraidStoreable is an autogenerated mock type for the UnraidStoreable type
type UnraidStoreable struct {
	mock.Mock
}

type UnraidStoreable_Expecter struct {
	mock *mock.Mock
}

func (_m *UnraidStoreable) EXPECT() *UnraidStoreable_Expecter {
	return &UnraidStoreable_Expecter{mock: &_m.Mock}
}

// GetFSPath provides a mock function with no fields
func (_m *UnraidStoreable) GetFSPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFSPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// UnraidStoreable_GetFSPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFSPath'
type UnraidStoreable_GetFSPath_Call struct {
	*mock.Call
}

// GetFSPath is a helper method to define mock.On call
func (_e *UnraidStoreable_Expecter) GetFSPath() *UnraidStoreable_GetFSPath_Call {
	return &UnraidStoreable_GetFSPath_Call{Call: _e.mock.On("GetFSPath")}
}

func (_c *UnraidStoreable_GetFSPath_Call) Run(run func()) *UnraidStoreable_GetFSPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnraidStoreable_GetFSPath_Call) Return(_a0 string) *UnraidStoreable_GetFSPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UnraidStoreable_GetFSPath_Call) RunAndReturn(run func() string) *UnraidStoreable_GetFSPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with no fields
func (_m *UnraidStoreable) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// UnraidStoreable_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type UnraidStoreable_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *UnraidStoreable_Expecter) GetName() *UnraidStoreable_GetName_Call {
	return &UnraidStoreable_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *UnraidStoreable_GetName_Call) Run(run func()) *UnraidStoreable_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnraidStoreable_GetName_Call) Return(_a0 string) *UnraidStoreable_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UnraidStoreable_GetName_Call) RunAndReturn(run func() string) *UnraidStoreable_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// IsActiveTransfer provides a mock function with no fields
func (_m *UnraidStoreable) IsActiveTransfer() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsActiveTransfer")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// UnraidStoreable_IsActiveTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsActiveTransfer'
type UnraidStoreable_IsActiveTransfer_Call struct {
	*mock.Call
}

// IsActiveTransfer is a helper method to define mock.On call
func (_e *UnraidStoreable_Expecter) IsActiveTransfer() *UnraidStoreable_IsActiveTransfer_Call {
	return &UnraidStoreable_IsActiveTransfer_Call{Call: _e.mock.On("IsActiveTransfer")}
}

func (_c *UnraidStoreable_IsActiveTransfer_Call) Run(run func()) *UnraidStoreable_IsActiveTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnraidStoreable_IsActiveTransfer_Call) Return(_a0 bool) *UnraidStoreable_IsActiveTransfer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UnraidStoreable_IsActiveTransfer_Call) RunAndReturn(run func() bool) *UnraidStoreable_IsActiveTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// SetActiveTransfer provides a mock function with given fields: _a0
func (_m *UnraidStoreable) SetActiveTransfer(_a0 bool) {
	_m.Called(_a0)
}

// UnraidStoreable_SetActiveTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActiveTransfer'
type UnraidStoreable_SetActiveTransfer_Call struct {
	*mock.Call
}

// SetActiveTransfer is a helper method to define mock.On call
//   - _a0 bool
func (_e *UnraidStoreable_Expecter) SetActiveTransfer(_a0 interface{}) *UnraidStoreable_SetActiveTransfer_Call {
	return &UnraidStoreable_SetActiveTransfer_Call{Call: _e.mock.On("SetActiveTransfer", _a0)}
}

func (_c *UnraidStoreable_SetActiveTransfer_Call) Run(run func(_a0 bool)) *UnraidStoreable_SetActiveTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *UnraidStoreable_SetActiveTransfer_Call) Return() *UnraidStoreable_SetActiveTransfer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnraidStoreable_SetActiveTransfer_Call) RunAndReturn(run func(bool)) *UnraidStoreable_SetActiveTransfer_Call {
	_c.Run(run)
	return _c
}

// NewUnraidStoreable creates a new instance of UnraidStoreable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnraidStoreable(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnraidStoreable {
	mock := &UnraidStoreable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
