// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package queue

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMock_GenericQueueType creates a new instance of Mock_GenericQueueType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_GenericQueueType[V comparable](t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_GenericQueueType[V] {
	mock := &Mock_GenericQueueType[V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mock_GenericQueueType is an autogenerated mock type for the GenericQueueType type
type Mock_GenericQueueType[V comparable] struct {
	mock.Mock
}

type Mock_GenericQueueType_Expecter[V comparable] struct {
	mock *mock.Mock
}

func (_m *Mock_GenericQueueType[V]) EXPECT() *Mock_GenericQueueType_Expecter[V] {
	return &Mock_GenericQueueType_Expecter[V]{mock: &_m.Mock}
}

// Enqueue provides a mock function for the type Mock_GenericQueueType
func (_mock *Mock_GenericQueueType[V]) Enqueue(items ...V) {
	// V
	_va := make([]interface{}, len(items))
	for _i := range items {
		_va[_i] = items[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// Mock_GenericQueueType_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type Mock_GenericQueueType_Enqueue_Call[V comparable] struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - items ...V
func (_e *Mock_GenericQueueType_Expecter[V]) Enqueue(items ...interface{}) *Mock_GenericQueueType_Enqueue_Call[V] {
	return &Mock_GenericQueueType_Enqueue_Call[V]{Call: _e.mock.On("Enqueue",
		append([]interface{}{}, items...)...)}
}

func (_c *Mock_GenericQueueType_Enqueue_Call[V]) Run(run func(items ...V)) *Mock_GenericQueueType_Enqueue_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []V
		variadicArgs := make([]V, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(V)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Mock_GenericQueueType_Enqueue_Call[V]) Return() *Mock_GenericQueueType_Enqueue_Call[V] {
	_c.Call.Return()
	return _c
}

func (_c *Mock_GenericQueueType_Enqueue_Call[V]) RunAndReturn(run func(items ...V)) *Mock_GenericQueueType_Enqueue_Call[V] {
	_c.Run(run)
	return _c
}

// GetSuccessful provides a mock function for the type Mock_GenericQueueType
func (_mock *Mock_GenericQueueType[V]) GetSuccessful() []V {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSuccessful")
	}

	var r0 []V
	if returnFunc, ok := ret.Get(0).(func() []V); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]V)
		}
	}
	return r0
}

// Mock_GenericQueueType_GetSuccessful_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSuccessful'
type Mock_GenericQueueType_GetSuccessful_Call[V comparable] struct {
	*mock.Call
}

// GetSuccessful is a helper method to define mock.On call
func (_e *Mock_GenericQueueType_Expecter[V]) GetSuccessful() *Mock_GenericQueueType_GetSuccessful_Call[V] {
	return &Mock_GenericQueueType_GetSuccessful_Call[V]{Call: _e.mock.On("GetSuccessful")}
}

func (_c *Mock_GenericQueueType_GetSuccessful_Call[V]) Run(run func()) *Mock_GenericQueueType_GetSuccessful_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_GenericQueueType_GetSuccessful_Call[V]) Return(vs []V) *Mock_GenericQueueType_GetSuccessful_Call[V] {
	_c.Call.Return(vs)
	return _c
}

func (_c *Mock_GenericQueueType_GetSuccessful_Call[V]) RunAndReturn(run func() []V) *Mock_GenericQueueType_GetSuccessful_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Progress provides a mock function for the type Mock_GenericQueueType
func (_mock *Mock_GenericQueueType[V]) Progress() Progress {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Progress")
	}

	var r0 Progress
	if returnFunc, ok := ret.Get(0).(func() Progress); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(Progress)
	}
	return r0
}

// Mock_GenericQueueType_Progress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Progress'
type Mock_GenericQueueType_Progress_Call[V comparable] struct {
	*mock.Call
}

// Progress is a helper method to define mock.On call
func (_e *Mock_GenericQueueType_Expecter[V]) Progress() *Mock_GenericQueueType_Progress_Call[V] {
	return &Mock_GenericQueueType_Progress_Call[V]{Call: _e.mock.On("Progress")}
}

func (_c *Mock_GenericQueueType_Progress_Call[V]) Run(run func()) *Mock_GenericQueueType_Progress_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_GenericQueueType_Progress_Call[V]) Return(progress Progress) *Mock_GenericQueueType_Progress_Call[V] {
	_c.Call.Return(progress)
	return _c
}

func (_c *Mock_GenericQueueType_Progress_Call[V]) RunAndReturn(run func() Progress) *Mock_GenericQueueType_Progress_Call[V] {
	_c.Call.Return(run)
	return _c
}
