// Code generated by mockery. DO NOT EDIT.

package queue

import mock "github.com/stretchr/testify/mock"

// MockGenericQueueType is an autogenerated mock type for the GenericQueueType type
type MockGenericQueueType[E comparable] struct {
	mock.Mock
}

type MockGenericQueueType_Expecter[E comparable] struct {
	mock *mock.Mock
}

func (_m *MockGenericQueueType[E]) EXPECT() *MockGenericQueueType_Expecter[E] {
	return &MockGenericQueueType_Expecter[E]{mock: &_m.Mock}
}

// Enqueue provides a mock function with given fields: items
func (_m *MockGenericQueueType[E]) Enqueue(items ...E) {
	_va := make([]interface{}, len(items))
	for _i := range items {
		_va[_i] = items[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockGenericQueueType_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockGenericQueueType_Enqueue_Call[E comparable] struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - items ...E
func (_e *MockGenericQueueType_Expecter[E]) Enqueue(items ...interface{}) *MockGenericQueueType_Enqueue_Call[E] {
	return &MockGenericQueueType_Enqueue_Call[E]{Call: _e.mock.On("Enqueue",
		append([]interface{}{}, items...)...)}
}

func (_c *MockGenericQueueType_Enqueue_Call[E]) Run(run func(items ...E)) *MockGenericQueueType_Enqueue_Call[E] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]E, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(E)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockGenericQueueType_Enqueue_Call[E]) Return() *MockGenericQueueType_Enqueue_Call[E] {
	_c.Call.Return()
	return _c
}

func (_c *MockGenericQueueType_Enqueue_Call[E]) RunAndReturn(run func(...E)) *MockGenericQueueType_Enqueue_Call[E] {
	_c.Run(run)
	return _c
}

// GetSuccessful provides a mock function with no fields
func (_m *MockGenericQueueType[E]) GetSuccessful() []E {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSuccessful")
	}

	var r0 []E
	if rf, ok := ret.Get(0).(func() []E); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]E)
		}
	}

	return r0
}

// MockGenericQueueType_GetSuccessful_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSuccessful'
type MockGenericQueueType_GetSuccessful_Call[E comparable] struct {
	*mock.Call
}

// GetSuccessful is a helper method to define mock.On call
func (_e *MockGenericQueueType_Expecter[E]) GetSuccessful() *MockGenericQueueType_GetSuccessful_Call[E] {
	return &MockGenericQueueType_GetSuccessful_Call[E]{Call: _e.mock.On("GetSuccessful")}
}

func (_c *MockGenericQueueType_GetSuccessful_Call[E]) Run(run func()) *MockGenericQueueType_GetSuccessful_Call[E] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGenericQueueType_GetSuccessful_Call[E]) Return(_a0 []E) *MockGenericQueueType_GetSuccessful_Call[E] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGenericQueueType_GetSuccessful_Call[E]) RunAndReturn(run func() []E) *MockGenericQueueType_GetSuccessful_Call[E] {
	_c.Call.Return(run)
	return _c
}

// Progress provides a mock function with no fields
func (_m *MockGenericQueueType[E]) Progress() Progress {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Progress")
	}

	var r0 Progress
	if rf, ok := ret.Get(0).(func() Progress); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Progress)
	}

	return r0
}

// MockGenericQueueType_Progress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Progress'
type MockGenericQueueType_Progress_Call[E comparable] struct {
	*mock.Call
}

// Progress is a helper method to define mock.On call
func (_e *MockGenericQueueType_Expecter[E]) Progress() *MockGenericQueueType_Progress_Call[E] {
	return &MockGenericQueueType_Progress_Call[E]{Call: _e.mock.On("Progress")}
}

func (_c *MockGenericQueueType_Progress_Call[E]) Run(run func()) *MockGenericQueueType_Progress_Call[E] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGenericQueueType_Progress_Call[E]) Return(_a0 Progress) *MockGenericQueueType_Progress_Call[E] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGenericQueueType_Progress_Call[E]) RunAndReturn(run func() Progress) *MockGenericQueueType_Progress_Call[E] {
	_c.Call.Return(run)
	return _c
}

// NewMockGenericQueueType creates a new instance of MockGenericQueueType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenericQueueType[E comparable](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenericQueueType[E] {
	mock := &MockGenericQueueType[E]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
