// Code generated by mockery. DO NOT EDIT.

package schema

import mock "github.com/stretchr/testify/mock"

// MockBatchProcessor is an autogenerated mock type for the BatchProcessor type
type MockBatchProcessor[T any] struct {
	mock.Mock
}

type MockBatchProcessor_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockBatchProcessor[T]) EXPECT() *MockBatchProcessor_Expecter[T] {
	return &MockBatchProcessor_Expecter[T]{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockBatchProcessor[T]) Execute(_a0 []T) ([]T, bool) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []T
	var r1 bool
	if rf, ok := ret.Get(0).(func([]T) ([]T, bool)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]T) []T); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}

	if rf, ok := ret.Get(1).(func([]T) bool); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockBatchProcessor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockBatchProcessor_Execute_Call[T any] struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 []T
func (_e *MockBatchProcessor_Expecter[T]) Execute(_a0 interface{}) *MockBatchProcessor_Execute_Call[T] {
	return &MockBatchProcessor_Execute_Call[T]{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockBatchProcessor_Execute_Call[T]) Run(run func(_a0 []T)) *MockBatchProcessor_Execute_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]T))
	})
	return _c
}

func (_c *MockBatchProcessor_Execute_Call[T]) Return(_a0 []T, _a1 bool) *MockBatchProcessor_Execute_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBatchProcessor_Execute_Call[T]) RunAndReturn(run func([]T) ([]T, bool)) *MockBatchProcessor_Execute_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockBatchProcessor creates a new instance of MockBatchProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatchProcessor[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatchProcessor[T] {
	mock := &MockBatchProcessor[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
