// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package schema

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMock_Pipeline creates a new instance of Mock_Pipeline. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_Pipeline[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_Pipeline[T] {
	mock := &Mock_Pipeline[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mock_Pipeline is an autogenerated mock type for the Pipeline type
type Mock_Pipeline[T any] struct {
	mock.Mock
}

type Mock_Pipeline_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *Mock_Pipeline[T]) EXPECT() *Mock_Pipeline_Expecter[T] {
	return &Mock_Pipeline_Expecter[T]{mock: &_m.Mock}
}

// Add provides a mock function for the type Mock_Pipeline
func (_mock *Mock_Pipeline[T]) Add(processor Processor[T]) Pipeline[T] {
	ret := _mock.Called(processor)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 Pipeline[T]
	if returnFunc, ok := ret.Get(0).(func(Processor[T]) Pipeline[T]); ok {
		r0 = returnFunc(processor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Pipeline[T])
		}
	}
	return r0
}

// Mock_Pipeline_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Mock_Pipeline_Add_Call[T any] struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - processor Processor[T]
func (_e *Mock_Pipeline_Expecter[T]) Add(processor interface{}) *Mock_Pipeline_Add_Call[T] {
	return &Mock_Pipeline_Add_Call[T]{Call: _e.mock.On("Add", processor)}
}

func (_c *Mock_Pipeline_Add_Call[T]) Run(run func(processor Processor[T])) *Mock_Pipeline_Add_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Processor[T]
		if args[0] != nil {
			arg0 = args[0].(Processor[T])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mock_Pipeline_Add_Call[T]) Return(pipeline Pipeline[T]) *Mock_Pipeline_Add_Call[T] {
	_c.Call.Return(pipeline)
	return _c
}

func (_c *Mock_Pipeline_Add_Call[T]) RunAndReturn(run func(processor Processor[T]) Pipeline[T]) *Mock_Pipeline_Add_Call[T] {
	_c.Call.Return(run)
	return _c
}

// AddPostProcess provides a mock function for the type Mock_Pipeline
func (_mock *Mock_Pipeline[T]) AddPostProcess(processor BatchProcessor[T]) Pipeline[T] {
	ret := _mock.Called(processor)

	if len(ret) == 0 {
		panic("no return value specified for AddPostProcess")
	}

	var r0 Pipeline[T]
	if returnFunc, ok := ret.Get(0).(func(BatchProcessor[T]) Pipeline[T]); ok {
		r0 = returnFunc(processor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Pipeline[T])
		}
	}
	return r0
}

// Mock_Pipeline_AddPostProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPostProcess'
type Mock_Pipeline_AddPostProcess_Call[T any] struct {
	*mock.Call
}

// AddPostProcess is a helper method to define mock.On call
//   - processor BatchProcessor[T]
func (_e *Mock_Pipeline_Expecter[T]) AddPostProcess(processor interface{}) *Mock_Pipeline_AddPostProcess_Call[T] {
	return &Mock_Pipeline_AddPostProcess_Call[T]{Call: _e.mock.On("AddPostProcess", processor)}
}

func (_c *Mock_Pipeline_AddPostProcess_Call[T]) Run(run func(processor BatchProcessor[T])) *Mock_Pipeline_AddPostProcess_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 BatchProcessor[T]
		if args[0] != nil {
			arg0 = args[0].(BatchProcessor[T])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mock_Pipeline_AddPostProcess_Call[T]) Return(pipeline Pipeline[T]) *Mock_Pipeline_AddPostProcess_Call[T] {
	_c.Call.Return(pipeline)
	return _c
}

func (_c *Mock_Pipeline_AddPostProcess_Call[T]) RunAndReturn(run func(processor BatchProcessor[T]) Pipeline[T]) *Mock_Pipeline_AddPostProcess_Call[T] {
	_c.Call.Return(run)
	return _c
}

// AddPreProcess provides a mock function for the type Mock_Pipeline
func (_mock *Mock_Pipeline[T]) AddPreProcess(processor BatchProcessor[T]) Pipeline[T] {
	ret := _mock.Called(processor)

	if len(ret) == 0 {
		panic("no return value specified for AddPreProcess")
	}

	var r0 Pipeline[T]
	if returnFunc, ok := ret.Get(0).(func(BatchProcessor[T]) Pipeline[T]); ok {
		r0 = returnFunc(processor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Pipeline[T])
		}
	}
	return r0
}

// Mock_Pipeline_AddPreProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPreProcess'
type Mock_Pipeline_AddPreProcess_Call[T any] struct {
	*mock.Call
}

// AddPreProcess is a helper method to define mock.On call
//   - processor BatchProcessor[T]
func (_e *Mock_Pipeline_Expecter[T]) AddPreProcess(processor interface{}) *Mock_Pipeline_AddPreProcess_Call[T] {
	return &Mock_Pipeline_AddPreProcess_Call[T]{Call: _e.mock.On("AddPreProcess", processor)}
}

func (_c *Mock_Pipeline_AddPreProcess_Call[T]) Run(run func(processor BatchProcessor[T])) *Mock_Pipeline_AddPreProcess_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 BatchProcessor[T]
		if args[0] != nil {
			arg0 = args[0].(BatchProcessor[T])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mock_Pipeline_AddPreProcess_Call[T]) Return(pipeline Pipeline[T]) *Mock_Pipeline_AddPreProcess_Call[T] {
	_c.Call.Return(pipeline)
	return _c
}

func (_c *Mock_Pipeline_AddPreProcess_Call[T]) RunAndReturn(run func(processor BatchProcessor[T]) Pipeline[T]) *Mock_Pipeline_AddPreProcess_Call[T] {
	_c.Call.Return(run)
	return _c
}

// PostProcess provides a mock function for the type Mock_Pipeline
func (_mock *Mock_Pipeline[T]) PostProcess(items []T) ([]T, bool) {
	ret := _mock.Called(items)

	if len(ret) == 0 {
		panic("no return value specified for PostProcess")
	}

	var r0 []T
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func([]T) ([]T, bool)); ok {
		return returnFunc(items)
	}
	if returnFunc, ok := ret.Get(0).(func([]T) []T); ok {
		r0 = returnFunc(items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]T) bool); ok {
		r1 = returnFunc(items)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// Mock_Pipeline_PostProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostProcess'
type Mock_Pipeline_PostProcess_Call[T any] struct {
	*mock.Call
}

// PostProcess is a helper method to define mock.On call
//   - items []T
func (_e *Mock_Pipeline_Expecter[T]) PostProcess(items interface{}) *Mock_Pipeline_PostProcess_Call[T] {
	return &Mock_Pipeline_PostProcess_Call[T]{Call: _e.mock.On("PostProcess", items)}
}

func (_c *Mock_Pipeline_PostProcess_Call[T]) Run(run func(items []T)) *Mock_Pipeline_PostProcess_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []T
		if args[0] != nil {
			arg0 = args[0].([]T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mock_Pipeline_PostProcess_Call[T]) Return(vs []T, b bool) *Mock_Pipeline_PostProcess_Call[T] {
	_c.Call.Return(vs, b)
	return _c
}

func (_c *Mock_Pipeline_PostProcess_Call[T]) RunAndReturn(run func(items []T) ([]T, bool)) *Mock_Pipeline_PostProcess_Call[T] {
	_c.Call.Return(run)
	return _c
}

// PreProcess provides a mock function for the type Mock_Pipeline
func (_mock *Mock_Pipeline[T]) PreProcess(items []T) ([]T, bool) {
	ret := _mock.Called(items)

	if len(ret) == 0 {
		panic("no return value specified for PreProcess")
	}

	var r0 []T
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func([]T) ([]T, bool)); ok {
		return returnFunc(items)
	}
	if returnFunc, ok := ret.Get(0).(func([]T) []T); ok {
		r0 = returnFunc(items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]T) bool); ok {
		r1 = returnFunc(items)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// Mock_Pipeline_PreProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreProcess'
type Mock_Pipeline_PreProcess_Call[T any] struct {
	*mock.Call
}

// PreProcess is a helper method to define mock.On call
//   - items []T
func (_e *Mock_Pipeline_Expecter[T]) PreProcess(items interface{}) *Mock_Pipeline_PreProcess_Call[T] {
	return &Mock_Pipeline_PreProcess_Call[T]{Call: _e.mock.On("PreProcess", items)}
}

func (_c *Mock_Pipeline_PreProcess_Call[T]) Run(run func(items []T)) *Mock_Pipeline_PreProcess_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []T
		if args[0] != nil {
			arg0 = args[0].([]T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mock_Pipeline_PreProcess_Call[T]) Return(vs []T, b bool) *Mock_Pipeline_PreProcess_Call[T] {
	_c.Call.Return(vs, b)
	return _c
}

func (_c *Mock_Pipeline_PreProcess_Call[T]) RunAndReturn(run func(items []T) ([]T, bool)) *Mock_Pipeline_PreProcess_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Process provides a mock function for the type Mock_Pipeline
func (_mock *Mock_Pipeline[T]) Process(item T) bool {
	ret := _mock.Called(item)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(T) bool); ok {
		r0 = returnFunc(item)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Mock_Pipeline_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type Mock_Pipeline_Process_Call[T any] struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - item T
func (_e *Mock_Pipeline_Expecter[T]) Process(item interface{}) *Mock_Pipeline_Process_Call[T] {
	return &Mock_Pipeline_Process_Call[T]{Call: _e.mock.On("Process", item)}
}

func (_c *Mock_Pipeline_Process_Call[T]) Run(run func(item T)) *Mock_Pipeline_Process_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Mock_Pipeline_Process_Call[T]) Return(b bool) *Mock_Pipeline_Process_Call[T] {
	_c.Call.Return(b)
	return _c
}

func (_c *Mock_Pipeline_Process_Call[T]) RunAndReturn(run func(item T) bool) *Mock_Pipeline_Process_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMock_Storage creates a new instance of Mock_Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_Storage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_Storage {
	mock := &Mock_Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mock_Storage is an autogenerated mock type for the Storage type
type Mock_Storage struct {
	mock.Mock
}

type Mock_Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_Storage) EXPECT() *Mock_Storage_Expecter {
	return &Mock_Storage_Expecter{mock: &_m.Mock}
}

// GetFSPath provides a mock function for the type Mock_Storage
func (_mock *Mock_Storage) GetFSPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFSPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Mock_Storage_GetFSPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFSPath'
type Mock_Storage_GetFSPath_Call struct {
	*mock.Call
}

// GetFSPath is a helper method to define mock.On call
func (_e *Mock_Storage_Expecter) GetFSPath() *Mock_Storage_GetFSPath_Call {
	return &Mock_Storage_GetFSPath_Call{Call: _e.mock.On("GetFSPath")}
}

func (_c *Mock_Storage_GetFSPath_Call) Run(run func()) *Mock_Storage_GetFSPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Storage_GetFSPath_Call) Return(s string) *Mock_Storage_GetFSPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Mock_Storage_GetFSPath_Call) RunAndReturn(run func() string) *Mock_Storage_GetFSPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type Mock_Storage
func (_mock *Mock_Storage) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Mock_Storage_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type Mock_Storage_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *Mock_Storage_Expecter) GetName() *Mock_Storage_GetName_Call {
	return &Mock_Storage_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *Mock_Storage_GetName_Call) Run(run func()) *Mock_Storage_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Storage_GetName_Call) Return(s string) *Mock_Storage_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Mock_Storage_GetName_Call) RunAndReturn(run func() string) *Mock_Storage_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_Disk creates a new instance of Mock_Disk. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_Disk(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_Disk {
	mock := &Mock_Disk{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mock_Disk is an autogenerated mock type for the Disk type
type Mock_Disk struct {
	mock.Mock
}

type Mock_Disk_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_Disk) EXPECT() *Mock_Disk_Expecter {
	return &Mock_Disk_Expecter{mock: &_m.Mock}
}

// GetFSPath provides a mock function for the type Mock_Disk
func (_mock *Mock_Disk) GetFSPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFSPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Mock_Disk_GetFSPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFSPath'
type Mock_Disk_GetFSPath_Call struct {
	*mock.Call
}

// GetFSPath is a helper method to define mock.On call
func (_e *Mock_Disk_Expecter) GetFSPath() *Mock_Disk_GetFSPath_Call {
	return &Mock_Disk_GetFSPath_Call{Call: _e.mock.On("GetFSPath")}
}

func (_c *Mock_Disk_GetFSPath_Call) Run(run func()) *Mock_Disk_GetFSPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Disk_GetFSPath_Call) Return(s string) *Mock_Disk_GetFSPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Mock_Disk_GetFSPath_Call) RunAndReturn(run func() string) *Mock_Disk_GetFSPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type Mock_Disk
func (_mock *Mock_Disk) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Mock_Disk_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type Mock_Disk_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *Mock_Disk_Expecter) GetName() *Mock_Disk_GetName_Call {
	return &Mock_Disk_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *Mock_Disk_GetName_Call) Run(run func()) *Mock_Disk_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Disk_GetName_Call) Return(s string) *Mock_Disk_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Mock_Disk_GetName_Call) RunAndReturn(run func() string) *Mock_Disk_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// IsDisk provides a mock function for the type Mock_Disk
func (_mock *Mock_Disk) IsDisk() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsDisk")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Mock_Disk_IsDisk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDisk'
type Mock_Disk_IsDisk_Call struct {
	*mock.Call
}

// IsDisk is a helper method to define mock.On call
func (_e *Mock_Disk_Expecter) IsDisk() *Mock_Disk_IsDisk_Call {
	return &Mock_Disk_IsDisk_Call{Call: _e.mock.On("IsDisk")}
}

func (_c *Mock_Disk_IsDisk_Call) Run(run func()) *Mock_Disk_IsDisk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Disk_IsDisk_Call) Return(b bool) *Mock_Disk_IsDisk_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Mock_Disk_IsDisk_Call) RunAndReturn(run func() bool) *Mock_Disk_IsDisk_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_Pool creates a new instance of Mock_Pool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_Pool(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_Pool {
	mock := &Mock_Pool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mock_Pool is an autogenerated mock type for the Pool type
type Mock_Pool struct {
	mock.Mock
}

type Mock_Pool_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_Pool) EXPECT() *Mock_Pool_Expecter {
	return &Mock_Pool_Expecter{mock: &_m.Mock}
}

// GetFSPath provides a mock function for the type Mock_Pool
func (_mock *Mock_Pool) GetFSPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFSPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Mock_Pool_GetFSPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFSPath'
type Mock_Pool_GetFSPath_Call struct {
	*mock.Call
}

// GetFSPath is a helper method to define mock.On call
func (_e *Mock_Pool_Expecter) GetFSPath() *Mock_Pool_GetFSPath_Call {
	return &Mock_Pool_GetFSPath_Call{Call: _e.mock.On("GetFSPath")}
}

func (_c *Mock_Pool_GetFSPath_Call) Run(run func()) *Mock_Pool_GetFSPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Pool_GetFSPath_Call) Return(s string) *Mock_Pool_GetFSPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Mock_Pool_GetFSPath_Call) RunAndReturn(run func() string) *Mock_Pool_GetFSPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type Mock_Pool
func (_mock *Mock_Pool) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Mock_Pool_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type Mock_Pool_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *Mock_Pool_Expecter) GetName() *Mock_Pool_GetName_Call {
	return &Mock_Pool_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *Mock_Pool_GetName_Call) Run(run func()) *Mock_Pool_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Pool_GetName_Call) Return(s string) *Mock_Pool_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Mock_Pool_GetName_Call) RunAndReturn(run func() string) *Mock_Pool_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// IsPool provides a mock function for the type Mock_Pool
func (_mock *Mock_Pool) IsPool() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsPool")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Mock_Pool_IsPool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPool'
type Mock_Pool_IsPool_Call struct {
	*mock.Call
}

// IsPool is a helper method to define mock.On call
func (_e *Mock_Pool_Expecter) IsPool() *Mock_Pool_IsPool_Call {
	return &Mock_Pool_IsPool_Call{Call: _e.mock.On("IsPool")}
}

func (_c *Mock_Pool_IsPool_Call) Run(run func()) *Mock_Pool_IsPool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Pool_IsPool_Call) Return(b bool) *Mock_Pool_IsPool_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Mock_Pool_IsPool_Call) RunAndReturn(run func() bool) *Mock_Pool_IsPool_Call {
	_c.Call.Return(run)
	return _c
}

// NewMock_Share creates a new instance of Mock_Share. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock_Share(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock_Share {
	mock := &Mock_Share{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Mock_Share is an autogenerated mock type for the Share type
type Mock_Share struct {
	mock.Mock
}

type Mock_Share_Expecter struct {
	mock *mock.Mock
}

func (_m *Mock_Share) EXPECT() *Mock_Share_Expecter {
	return &Mock_Share_Expecter{mock: &_m.Mock}
}

// GetAllocator provides a mock function for the type Mock_Share
func (_mock *Mock_Share) GetAllocator() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllocator")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Mock_Share_GetAllocator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllocator'
type Mock_Share_GetAllocator_Call struct {
	*mock.Call
}

// GetAllocator is a helper method to define mock.On call
func (_e *Mock_Share_Expecter) GetAllocator() *Mock_Share_GetAllocator_Call {
	return &Mock_Share_GetAllocator_Call{Call: _e.mock.On("GetAllocator")}
}

func (_c *Mock_Share_GetAllocator_Call) Run(run func()) *Mock_Share_GetAllocator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Share_GetAllocator_Call) Return(s string) *Mock_Share_GetAllocator_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Mock_Share_GetAllocator_Call) RunAndReturn(run func() string) *Mock_Share_GetAllocator_Call {
	_c.Call.Return(run)
	return _c
}

// GetCachePool provides a mock function for the type Mock_Share
func (_mock *Mock_Share) GetCachePool() Pool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCachePool")
	}

	var r0 Pool
	if returnFunc, ok := ret.Get(0).(func() Pool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Pool)
		}
	}
	return r0
}

// Mock_Share_GetCachePool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCachePool'
type Mock_Share_GetCachePool_Call struct {
	*mock.Call
}

// GetCachePool is a helper method to define mock.On call
func (_e *Mock_Share_Expecter) GetCachePool() *Mock_Share_GetCachePool_Call {
	return &Mock_Share_GetCachePool_Call{Call: _e.mock.On("GetCachePool")}
}

func (_c *Mock_Share_GetCachePool_Call) Run(run func()) *Mock_Share_GetCachePool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Share_GetCachePool_Call) Return(pool Pool) *Mock_Share_GetCachePool_Call {
	_c.Call.Return(pool)
	return _c
}

func (_c *Mock_Share_GetCachePool_Call) RunAndReturn(run func() Pool) *Mock_Share_GetCachePool_Call {
	_c.Call.Return(run)
	return _c
}

// GetCachePool2 provides a mock function for the type Mock_Share
func (_mock *Mock_Share) GetCachePool2() Pool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCachePool2")
	}

	var r0 Pool
	if returnFunc, ok := ret.Get(0).(func() Pool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Pool)
		}
	}
	return r0
}

// Mock_Share_GetCachePool2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCachePool2'
type Mock_Share_GetCachePool2_Call struct {
	*mock.Call
}

// GetCachePool2 is a helper method to define mock.On call
func (_e *Mock_Share_Expecter) GetCachePool2() *Mock_Share_GetCachePool2_Call {
	return &Mock_Share_GetCachePool2_Call{Call: _e.mock.On("GetCachePool2")}
}

func (_c *Mock_Share_GetCachePool2_Call) Run(run func()) *Mock_Share_GetCachePool2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Share_GetCachePool2_Call) Return(pool Pool) *Mock_Share_GetCachePool2_Call {
	_c.Call.Return(pool)
	return _c
}

func (_c *Mock_Share_GetCachePool2_Call) RunAndReturn(run func() Pool) *Mock_Share_GetCachePool2_Call {
	_c.Call.Return(run)
	return _c
}

// GetDisableCOW provides a mock function for the type Mock_Share
func (_mock *Mock_Share) GetDisableCOW() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDisableCOW")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Mock_Share_GetDisableCOW_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDisableCOW'
type Mock_Share_GetDisableCOW_Call struct {
	*mock.Call
}

// GetDisableCOW is a helper method to define mock.On call
func (_e *Mock_Share_Expecter) GetDisableCOW() *Mock_Share_GetDisableCOW_Call {
	return &Mock_Share_GetDisableCOW_Call{Call: _e.mock.On("GetDisableCOW")}
}

func (_c *Mock_Share_GetDisableCOW_Call) Run(run func()) *Mock_Share_GetDisableCOW_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Share_GetDisableCOW_Call) Return(b bool) *Mock_Share_GetDisableCOW_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Mock_Share_GetDisableCOW_Call) RunAndReturn(run func() bool) *Mock_Share_GetDisableCOW_Call {
	_c.Call.Return(run)
	return _c
}

// GetIncludedDisks provides a mock function for the type Mock_Share
func (_mock *Mock_Share) GetIncludedDisks() map[string]Disk {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetIncludedDisks")
	}

	var r0 map[string]Disk
	if returnFunc, ok := ret.Get(0).(func() map[string]Disk); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]Disk)
		}
	}
	return r0
}

// Mock_Share_GetIncludedDisks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIncludedDisks'
type Mock_Share_GetIncludedDisks_Call struct {
	*mock.Call
}

// GetIncludedDisks is a helper method to define mock.On call
func (_e *Mock_Share_Expecter) GetIncludedDisks() *Mock_Share_GetIncludedDisks_Call {
	return &Mock_Share_GetIncludedDisks_Call{Call: _e.mock.On("GetIncludedDisks")}
}

func (_c *Mock_Share_GetIncludedDisks_Call) Run(run func()) *Mock_Share_GetIncludedDisks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Share_GetIncludedDisks_Call) Return(stringToDisk map[string]Disk) *Mock_Share_GetIncludedDisks_Call {
	_c.Call.Return(stringToDisk)
	return _c
}

func (_c *Mock_Share_GetIncludedDisks_Call) RunAndReturn(run func() map[string]Disk) *Mock_Share_GetIncludedDisks_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type Mock_Share
func (_mock *Mock_Share) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Mock_Share_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type Mock_Share_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *Mock_Share_Expecter) GetName() *Mock_Share_GetName_Call {
	return &Mock_Share_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *Mock_Share_GetName_Call) Run(run func()) *Mock_Share_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Share_GetName_Call) Return(s string) *Mock_Share_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Mock_Share_GetName_Call) RunAndReturn(run func() string) *Mock_Share_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// GetSpaceFloor provides a mock function for the type Mock_Share
func (_mock *Mock_Share) GetSpaceFloor() uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSpaceFloor")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// Mock_Share_GetSpaceFloor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSpaceFloor'
type Mock_Share_GetSpaceFloor_Call struct {
	*mock.Call
}

// GetSpaceFloor is a helper method to define mock.On call
func (_e *Mock_Share_Expecter) GetSpaceFloor() *Mock_Share_GetSpaceFloor_Call {
	return &Mock_Share_GetSpaceFloor_Call{Call: _e.mock.On("GetSpaceFloor")}
}

func (_c *Mock_Share_GetSpaceFloor_Call) Run(run func()) *Mock_Share_GetSpaceFloor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Share_GetSpaceFloor_Call) Return(v uint64) *Mock_Share_GetSpaceFloor_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *Mock_Share_GetSpaceFloor_Call) RunAndReturn(run func() uint64) *Mock_Share_GetSpaceFloor_Call {
	_c.Call.Return(run)
	return _c
}

// GetSplitLevel provides a mock function for the type Mock_Share
func (_mock *Mock_Share) GetSplitLevel() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSplitLevel")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// Mock_Share_GetSplitLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSplitLevel'
type Mock_Share_GetSplitLevel_Call struct {
	*mock.Call
}

// GetSplitLevel is a helper method to define mock.On call
func (_e *Mock_Share_Expecter) GetSplitLevel() *Mock_Share_GetSplitLevel_Call {
	return &Mock_Share_GetSplitLevel_Call{Call: _e.mock.On("GetSplitLevel")}
}

func (_c *Mock_Share_GetSplitLevel_Call) Run(run func()) *Mock_Share_GetSplitLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Share_GetSplitLevel_Call) Return(n int) *Mock_Share_GetSplitLevel_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *Mock_Share_GetSplitLevel_Call) RunAndReturn(run func() int) *Mock_Share_GetSplitLevel_Call {
	_c.Call.Return(run)
	return _c
}

// GetUseCache provides a mock function for the type Mock_Share
func (_mock *Mock_Share) GetUseCache() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUseCache")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Mock_Share_GetUseCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUseCache'
type Mock_Share_GetUseCache_Call struct {
	*mock.Call
}

// GetUseCache is a helper method to define mock.On call
func (_e *Mock_Share_Expecter) GetUseCache() *Mock_Share_GetUseCache_Call {
	return &Mock_Share_GetUseCache_Call{Call: _e.mock.On("GetUseCache")}
}

func (_c *Mock_Share_GetUseCache_Call) Run(run func()) *Mock_Share_GetUseCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mock_Share_GetUseCache_Call) Return(s string) *Mock_Share_GetUseCache_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Mock_Share_GetUseCache_Call) RunAndReturn(run func() string) *Mock_Share_GetUseCache_Call {
	_c.Call.Return(run)
	return _c
}
