// Code generated by mockery. DO NOT EDIT.

package schema

import mock "github.com/stretchr/testify/mock"

// MockDisk is an autogenerated mock type for the Disk type
type MockDisk struct {
	mock.Mock
}

type MockDisk_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDisk) EXPECT() *MockDisk_Expecter {
	return &MockDisk_Expecter{mock: &_m.Mock}
}

// GetFSPath provides a mock function with no fields
func (_m *MockDisk) GetFSPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFSPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDisk_GetFSPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFSPath'
type MockDisk_GetFSPath_Call struct {
	*mock.Call
}

// GetFSPath is a helper method to define mock.On call
func (_e *MockDisk_Expecter) GetFSPath() *MockDisk_GetFSPath_Call {
	return &MockDisk_GetFSPath_Call{Call: _e.mock.On("GetFSPath")}
}

func (_c *MockDisk_GetFSPath_Call) Run(run func()) *MockDisk_GetFSPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDisk_GetFSPath_Call) Return(_a0 string) *MockDisk_GetFSPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDisk_GetFSPath_Call) RunAndReturn(run func() string) *MockDisk_GetFSPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with no fields
func (_m *MockDisk) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDisk_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockDisk_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockDisk_Expecter) GetName() *MockDisk_GetName_Call {
	return &MockDisk_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockDisk_GetName_Call) Run(run func()) *MockDisk_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDisk_GetName_Call) Return(_a0 string) *MockDisk_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDisk_GetName_Call) RunAndReturn(run func() string) *MockDisk_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// IsDisk provides a mock function with no fields
func (_m *MockDisk) IsDisk() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsDisk")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockDisk_IsDisk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDisk'
type MockDisk_IsDisk_Call struct {
	*mock.Call
}

// IsDisk is a helper method to define mock.On call
func (_e *MockDisk_Expecter) IsDisk() *MockDisk_IsDisk_Call {
	return &MockDisk_IsDisk_Call{Call: _e.mock.On("IsDisk")}
}

func (_c *MockDisk_IsDisk_Call) Run(run func()) *MockDisk_IsDisk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDisk_IsDisk_Call) Return(_a0 bool) *MockDisk_IsDisk_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDisk_IsDisk_Call) RunAndReturn(run func() bool) *MockDisk_IsDisk_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDisk creates a new instance of MockDisk. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDisk(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDisk {
	mock := &MockDisk{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
