// Code generated by mockery. DO NOT EDIT.

package schema

import mock "github.com/stretchr/testify/mock"

// MockPool is an autogenerated mock type for the Pool type
type MockPool struct {
	mock.Mock
}

type MockPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPool) EXPECT() *MockPool_Expecter {
	return &MockPool_Expecter{mock: &_m.Mock}
}

// GetFSPath provides a mock function with no fields
func (_m *MockPool) GetFSPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFSPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPool_GetFSPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFSPath'
type MockPool_GetFSPath_Call struct {
	*mock.Call
}

// GetFSPath is a helper method to define mock.On call
func (_e *MockPool_Expecter) GetFSPath() *MockPool_GetFSPath_Call {
	return &MockPool_GetFSPath_Call{Call: _e.mock.On("GetFSPath")}
}

func (_c *MockPool_GetFSPath_Call) Run(run func()) *MockPool_GetFSPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPool_GetFSPath_Call) Return(_a0 string) *MockPool_GetFSPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPool_GetFSPath_Call) RunAndReturn(run func() string) *MockPool_GetFSPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with no fields
func (_m *MockPool) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPool_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockPool_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockPool_Expecter) GetName() *MockPool_GetName_Call {
	return &MockPool_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockPool_GetName_Call) Run(run func()) *MockPool_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPool_GetName_Call) Return(_a0 string) *MockPool_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPool_GetName_Call) RunAndReturn(run func() string) *MockPool_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// IsPool provides a mock function with no fields
func (_m *MockPool) IsPool() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsPool")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockPool_IsPool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPool'
type MockPool_IsPool_Call struct {
	*mock.Call
}

// IsPool is a helper method to define mock.On call
func (_e *MockPool_Expecter) IsPool() *MockPool_IsPool_Call {
	return &MockPool_IsPool_Call{Call: _e.mock.On("IsPool")}
}

func (_c *MockPool_IsPool_Call) Run(run func()) *MockPool_IsPool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPool_IsPool_Call) Return(_a0 bool) *MockPool_IsPool_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPool_IsPool_Call) RunAndReturn(run func() bool) *MockPool_IsPool_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPool creates a new instance of MockPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPool {
	mock := &MockPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
