// Code generated by mockery. DO NOT EDIT.

package schema

import mock "github.com/stretchr/testify/mock"

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// GetFSPath provides a mock function with no fields
func (_m *MockStorage) GetFSPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFSPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockStorage_GetFSPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFSPath'
type MockStorage_GetFSPath_Call struct {
	*mock.Call
}

// GetFSPath is a helper method to define mock.On call
func (_e *MockStorage_Expecter) GetFSPath() *MockStorage_GetFSPath_Call {
	return &MockStorage_GetFSPath_Call{Call: _e.mock.On("GetFSPath")}
}

func (_c *MockStorage_GetFSPath_Call) Run(run func()) *MockStorage_GetFSPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_GetFSPath_Call) Return(_a0 string) *MockStorage_GetFSPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_GetFSPath_Call) RunAndReturn(run func() string) *MockStorage_GetFSPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with no fields
func (_m *MockStorage) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockStorage_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockStorage_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockStorage_Expecter) GetName() *MockStorage_GetName_Call {
	return &MockStorage_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockStorage_GetName_Call) Run(run func()) *MockStorage_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_GetName_Call) Return(_a0 string) *MockStorage_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_GetName_Call) RunAndReturn(run func() string) *MockStorage_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
