// Code generated by mockery. DO NOT EDIT.

package schema

import mock "github.com/stretchr/testify/mock"

// MockProcessor is an autogenerated mock type for the Processor type
type MockProcessor struct {
	mock.Mock
}

type MockProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessor) EXPECT() *MockProcessor_Expecter {
	return &MockProcessor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockProcessor) Execute(_a0 *Moveable) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*Moveable) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockProcessor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockProcessor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *Moveable
func (_e *MockProcessor_Expecter) Execute(_a0 interface{}) *MockProcessor_Execute_Call {
	return &MockProcessor_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockProcessor_Execute_Call) Run(run func(_a0 *Moveable)) *MockProcessor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Moveable))
	})
	return _c
}

func (_c *MockProcessor_Execute_Call) Return(_a0 bool) *MockProcessor_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProcessor_Execute_Call) RunAndReturn(run func(*Moveable) bool) *MockProcessor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProcessor creates a new instance of MockProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessor {
	mock := &MockProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
