// Code generated by mockery. DO NOT EDIT.

package io

import (
	schema "github.com/desertwitch/gover/internal/schema"
	mock "github.com/stretchr/testify/mock"
)

// mockFsProvider is an autogenerated mock type for the fsProvider type
type mockFsProvider struct {
	mock.Mock
}

type mockFsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockFsProvider) EXPECT() *mockFsProvider_Expecter {
	return &mockFsProvider_Expecter{mock: &_m.Mock}
}

// HasEnoughFreeSpace provides a mock function with given fields: s, minFree, fileSize
func (_m *mockFsProvider) HasEnoughFreeSpace(s schema.Storage, minFree uint64, fileSize uint64) (bool, error) {
	ret := _m.Called(s, minFree, fileSize)

	if len(ret) == 0 {
		panic("no return value specified for HasEnoughFreeSpace")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(schema.Storage, uint64, uint64) (bool, error)); ok {
		return rf(s, minFree, fileSize)
	}
	if rf, ok := ret.Get(0).(func(schema.Storage, uint64, uint64) bool); ok {
		r0 = rf(s, minFree, fileSize)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(schema.Storage, uint64, uint64) error); ok {
		r1 = rf(s, minFree, fileSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockFsProvider_HasEnoughFreeSpace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasEnoughFreeSpace'
type mockFsProvider_HasEnoughFreeSpace_Call struct {
	*mock.Call
}

// HasEnoughFreeSpace is a helper method to define mock.On call
//   - s schema.Storage
//   - minFree uint64
//   - fileSize uint64
func (_e *mockFsProvider_Expecter) HasEnoughFreeSpace(s interface{}, minFree interface{}, fileSize interface{}) *mockFsProvider_HasEnoughFreeSpace_Call {
	return &mockFsProvider_HasEnoughFreeSpace_Call{Call: _e.mock.On("HasEnoughFreeSpace", s, minFree, fileSize)}
}

func (_c *mockFsProvider_HasEnoughFreeSpace_Call) Run(run func(s schema.Storage, minFree uint64, fileSize uint64)) *mockFsProvider_HasEnoughFreeSpace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(schema.Storage), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *mockFsProvider_HasEnoughFreeSpace_Call) Return(_a0 bool, _a1 error) *mockFsProvider_HasEnoughFreeSpace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockFsProvider_HasEnoughFreeSpace_Call) RunAndReturn(run func(schema.Storage, uint64, uint64) (bool, error)) *mockFsProvider_HasEnoughFreeSpace_Call {
	_c.Call.Return(run)
	return _c
}

// IsEmptyFolder provides a mock function with given fields: path
func (_m *mockFsProvider) IsEmptyFolder(path string) (bool, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for IsEmptyFolder")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockFsProvider_IsEmptyFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEmptyFolder'
type mockFsProvider_IsEmptyFolder_Call struct {
	*mock.Call
}

// IsEmptyFolder is a helper method to define mock.On call
//   - path string
func (_e *mockFsProvider_Expecter) IsEmptyFolder(path interface{}) *mockFsProvider_IsEmptyFolder_Call {
	return &mockFsProvider_IsEmptyFolder_Call{Call: _e.mock.On("IsEmptyFolder", path)}
}

func (_c *mockFsProvider_IsEmptyFolder_Call) Run(run func(path string)) *mockFsProvider_IsEmptyFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockFsProvider_IsEmptyFolder_Call) Return(_a0 bool, _a1 error) *mockFsProvider_IsEmptyFolder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockFsProvider_IsEmptyFolder_Call) RunAndReturn(run func(string) (bool, error)) *mockFsProvider_IsEmptyFolder_Call {
	_c.Call.Return(run)
	return _c
}

// IsInUse provides a mock function with given fields: path
func (_m *mockFsProvider) IsInUse(path string) bool {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for IsInUse")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// mockFsProvider_IsInUse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInUse'
type mockFsProvider_IsInUse_Call struct {
	*mock.Call
}

// IsInUse is a helper method to define mock.On call
//   - path string
func (_e *mockFsProvider_Expecter) IsInUse(path interface{}) *mockFsProvider_IsInUse_Call {
	return &mockFsProvider_IsInUse_Call{Call: _e.mock.On("IsInUse", path)}
}

func (_c *mockFsProvider_IsInUse_Call) Run(run func(path string)) *mockFsProvider_IsInUse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockFsProvider_IsInUse_Call) Return(_a0 bool) *mockFsProvider_IsInUse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockFsProvider_IsInUse_Call) RunAndReturn(run func(string) bool) *mockFsProvider_IsInUse_Call {
	_c.Call.Return(run)
	return _c
}

// newMockFsProvider creates a new instance of mockFsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockFsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockFsProvider {
	mock := &mockFsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
