// Code generated by mockery. DO NOT EDIT.

package allocation

import (
	filesystem "github.com/desertwitch/gover/internal/filesystem"
	mock "github.com/stretchr/testify/mock"

	schema "github.com/desertwitch/gover/internal/schema"
)

// mockFsProvider is an autogenerated mock type for the fsProvider type
type mockFsProvider struct {
	mock.Mock
}

type mockFsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockFsProvider) EXPECT() *mockFsProvider_Expecter {
	return &mockFsProvider_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function with given fields: path
func (_m *mockFsProvider) Exists(path string) (bool, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockFsProvider_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type mockFsProvider_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - path string
func (_e *mockFsProvider_Expecter) Exists(path interface{}) *mockFsProvider_Exists_Call {
	return &mockFsProvider_Exists_Call{Call: _e.mock.On("Exists", path)}
}

func (_c *mockFsProvider_Exists_Call) Run(run func(path string)) *mockFsProvider_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockFsProvider_Exists_Call) Return(_a0 bool, _a1 error) *mockFsProvider_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockFsProvider_Exists_Call) RunAndReturn(run func(string) (bool, error)) *mockFsProvider_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetDiskUsage provides a mock function with given fields: s
func (_m *mockFsProvider) GetDiskUsage(s schema.Storage) (filesystem.DiskStats, error) {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetDiskUsage")
	}

	var r0 filesystem.DiskStats
	var r1 error
	if rf, ok := ret.Get(0).(func(schema.Storage) (filesystem.DiskStats, error)); ok {
		return rf(s)
	}
	if rf, ok := ret.Get(0).(func(schema.Storage) filesystem.DiskStats); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Get(0).(filesystem.DiskStats)
	}

	if rf, ok := ret.Get(1).(func(schema.Storage) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockFsProvider_GetDiskUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDiskUsage'
type mockFsProvider_GetDiskUsage_Call struct {
	*mock.Call
}

// GetDiskUsage is a helper method to define mock.On call
//   - s schema.Storage
func (_e *mockFsProvider_Expecter) GetDiskUsage(s interface{}) *mockFsProvider_GetDiskUsage_Call {
	return &mockFsProvider_GetDiskUsage_Call{Call: _e.mock.On("GetDiskUsage", s)}
}

func (_c *mockFsProvider_GetDiskUsage_Call) Run(run func(s schema.Storage)) *mockFsProvider_GetDiskUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(schema.Storage))
	})
	return _c
}

func (_c *mockFsProvider_GetDiskUsage_Call) Return(_a0 filesystem.DiskStats, _a1 error) *mockFsProvider_GetDiskUsage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockFsProvider_GetDiskUsage_Call) RunAndReturn(run func(schema.Storage) (filesystem.DiskStats, error)) *mockFsProvider_GetDiskUsage_Call {
	_c.Call.Return(run)
	return _c
}

// HasEnoughFreeSpace provides a mock function with given fields: s, minFree, fileSize
func (_m *mockFsProvider) HasEnoughFreeSpace(s schema.Storage, minFree uint64, fileSize uint64) (bool, error) {
	ret := _m.Called(s, minFree, fileSize)

	if len(ret) == 0 {
		panic("no return value specified for HasEnoughFreeSpace")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(schema.Storage, uint64, uint64) (bool, error)); ok {
		return rf(s, minFree, fileSize)
	}
	if rf, ok := ret.Get(0).(func(schema.Storage, uint64, uint64) bool); ok {
		r0 = rf(s, minFree, fileSize)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(schema.Storage, uint64, uint64) error); ok {
		r1 = rf(s, minFree, fileSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockFsProvider_HasEnoughFreeSpace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasEnoughFreeSpace'
type mockFsProvider_HasEnoughFreeSpace_Call struct {
	*mock.Call
}

// HasEnoughFreeSpace is a helper method to define mock.On call
//   - s schema.Storage
//   - minFree uint64
//   - fileSize uint64
func (_e *mockFsProvider_Expecter) HasEnoughFreeSpace(s interface{}, minFree interface{}, fileSize interface{}) *mockFsProvider_HasEnoughFreeSpace_Call {
	return &mockFsProvider_HasEnoughFreeSpace_Call{Call: _e.mock.On("HasEnoughFreeSpace", s, minFree, fileSize)}
}

func (_c *mockFsProvider_HasEnoughFreeSpace_Call) Run(run func(s schema.Storage, minFree uint64, fileSize uint64)) *mockFsProvider_HasEnoughFreeSpace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(schema.Storage), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *mockFsProvider_HasEnoughFreeSpace_Call) Return(_a0 bool, _a1 error) *mockFsProvider_HasEnoughFreeSpace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockFsProvider_HasEnoughFreeSpace_Call) RunAndReturn(run func(schema.Storage, uint64, uint64) (bool, error)) *mockFsProvider_HasEnoughFreeSpace_Call {
	_c.Call.Return(run)
	return _c
}

// newMockFsProvider creates a new instance of mockFsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockFsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockFsProvider {
	mock := &mockFsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
