// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package allocation

import (
	"github.com/desertwitch/gover/internal/filesystem"
	"github.com/desertwitch/gover/internal/schema"
	mock "github.com/stretchr/testify/mock"
)

// newMock_fsProvider creates a new instance of mock_fsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMock_fsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mock_fsProvider {
	mock := &mock_fsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mock_fsProvider is an autogenerated mock type for the fsProvider type
type mock_fsProvider struct {
	mock.Mock
}

type mock_fsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mock_fsProvider) EXPECT() *mock_fsProvider_Expecter {
	return &mock_fsProvider_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function for the type mock_fsProvider
func (_mock *mock_fsProvider) Exists(path string) (bool, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mock_fsProvider_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type mock_fsProvider_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - path string
func (_e *mock_fsProvider_Expecter) Exists(path interface{}) *mock_fsProvider_Exists_Call {
	return &mock_fsProvider_Exists_Call{Call: _e.mock.On("Exists", path)}
}

func (_c *mock_fsProvider_Exists_Call) Run(run func(path string)) *mock_fsProvider_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mock_fsProvider_Exists_Call) Return(b bool, err error) *mock_fsProvider_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mock_fsProvider_Exists_Call) RunAndReturn(run func(path string) (bool, error)) *mock_fsProvider_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetDiskUsage provides a mock function for the type mock_fsProvider
func (_mock *mock_fsProvider) GetDiskUsage(s schema.Storage) (filesystem.DiskStats, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetDiskUsage")
	}

	var r0 filesystem.DiskStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(schema.Storage) (filesystem.DiskStats, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(schema.Storage) filesystem.DiskStats); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(filesystem.DiskStats)
	}
	if returnFunc, ok := ret.Get(1).(func(schema.Storage) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mock_fsProvider_GetDiskUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDiskUsage'
type mock_fsProvider_GetDiskUsage_Call struct {
	*mock.Call
}

// GetDiskUsage is a helper method to define mock.On call
//   - s schema.Storage
func (_e *mock_fsProvider_Expecter) GetDiskUsage(s interface{}) *mock_fsProvider_GetDiskUsage_Call {
	return &mock_fsProvider_GetDiskUsage_Call{Call: _e.mock.On("GetDiskUsage", s)}
}

func (_c *mock_fsProvider_GetDiskUsage_Call) Run(run func(s schema.Storage)) *mock_fsProvider_GetDiskUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 schema.Storage
		if args[0] != nil {
			arg0 = args[0].(schema.Storage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mock_fsProvider_GetDiskUsage_Call) Return(diskStats filesystem.DiskStats, err error) *mock_fsProvider_GetDiskUsage_Call {
	_c.Call.Return(diskStats, err)
	return _c
}

func (_c *mock_fsProvider_GetDiskUsage_Call) RunAndReturn(run func(s schema.Storage) (filesystem.DiskStats, error)) *mock_fsProvider_GetDiskUsage_Call {
	_c.Call.Return(run)
	return _c
}

// HasEnoughFreeSpace provides a mock function for the type mock_fsProvider
func (_mock *mock_fsProvider) HasEnoughFreeSpace(s schema.Storage, minFree uint64, fileSize uint64) (bool, error) {
	ret := _mock.Called(s, minFree, fileSize)

	if len(ret) == 0 {
		panic("no return value specified for HasEnoughFreeSpace")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(schema.Storage, uint64, uint64) (bool, error)); ok {
		return returnFunc(s, minFree, fileSize)
	}
	if returnFunc, ok := ret.Get(0).(func(schema.Storage, uint64, uint64) bool); ok {
		r0 = returnFunc(s, minFree, fileSize)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(schema.Storage, uint64, uint64) error); ok {
		r1 = returnFunc(s, minFree, fileSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mock_fsProvider_HasEnoughFreeSpace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasEnoughFreeSpace'
type mock_fsProvider_HasEnoughFreeSpace_Call struct {
	*mock.Call
}

// HasEnoughFreeSpace is a helper method to define mock.On call
//   - s schema.Storage
//   - minFree uint64
//   - fileSize uint64
func (_e *mock_fsProvider_Expecter) HasEnoughFreeSpace(s interface{}, minFree interface{}, fileSize interface{}) *mock_fsProvider_HasEnoughFreeSpace_Call {
	return &mock_fsProvider_HasEnoughFreeSpace_Call{Call: _e.mock.On("HasEnoughFreeSpace", s, minFree, fileSize)}
}

func (_c *mock_fsProvider_HasEnoughFreeSpace_Call) Run(run func(s schema.Storage, minFree uint64, fileSize uint64)) *mock_fsProvider_HasEnoughFreeSpace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 schema.Storage
		if args[0] != nil {
			arg0 = args[0].(schema.Storage)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint64
		if args[2] != nil {
			arg2 = args[2].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mock_fsProvider_HasEnoughFreeSpace_Call) Return(b bool, err error) *mock_fsProvider_HasEnoughFreeSpace_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mock_fsProvider_HasEnoughFreeSpace_Call) RunAndReturn(run func(s schema.Storage, minFree uint64, fileSize uint64) (bool, error)) *mock_fsProvider_HasEnoughFreeSpace_Call {
	_c.Call.Return(run)
	return _c
}
