// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ui

import (
	"github.com/charmbracelet/bubbletea"
	mock "github.com/stretchr/testify/mock"
)

// newMock_teaProgramProvider creates a new instance of mock_teaProgramProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMock_teaProgramProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mock_teaProgramProvider {
	mock := &mock_teaProgramProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mock_teaProgramProvider is an autogenerated mock type for the teaProgramProvider type
type mock_teaProgramProvider struct {
	mock.Mock
}

type mock_teaProgramProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mock_teaProgramProvider) EXPECT() *mock_teaProgramProvider_Expecter {
	return &mock_teaProgramProvider_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type mock_teaProgramProvider
func (_mock *mock_teaProgramProvider) Send(msg tea.Msg) {
	_mock.Called(msg)
	return
}

// mock_teaProgramProvider_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type mock_teaProgramProvider_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - msg tea.Msg
func (_e *mock_teaProgramProvider_Expecter) Send(msg interface{}) *mock_teaProgramProvider_Send_Call {
	return &mock_teaProgramProvider_Send_Call{Call: _e.mock.On("Send", msg)}
}

func (_c *mock_teaProgramProvider_Send_Call) Run(run func(msg tea.Msg)) *mock_teaProgramProvider_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tea.Msg
		if args[0] != nil {
			arg0 = args[0].(tea.Msg)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mock_teaProgramProvider_Send_Call) Return() *mock_teaProgramProvider_Send_Call {
	_c.Call.Return()
	return _c
}

func (_c *mock_teaProgramProvider_Send_Call) RunAndReturn(run func(msg tea.Msg)) *mock_teaProgramProvider_Send_Call {
	_c.Run(run)
	return _c
}
