// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pathing

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// newMock_osProvider creates a new instance of mock_osProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMock_osProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mock_osProvider {
	mock := &mock_osProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mock_osProvider is an autogenerated mock type for the osProvider type
type mock_osProvider struct {
	mock.Mock
}

type mock_osProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mock_osProvider) EXPECT() *mock_osProvider_Expecter {
	return &mock_osProvider_Expecter{mock: &_m.Mock}
}

// Stat provides a mock function for the type mock_osProvider
func (_mock *mock_osProvider) Stat(name string) (os.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mock_osProvider_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type mock_osProvider_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *mock_osProvider_Expecter) Stat(name interface{}) *mock_osProvider_Stat_Call {
	return &mock_osProvider_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *mock_osProvider_Stat_Call) Run(run func(name string)) *mock_osProvider_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mock_osProvider_Stat_Call) Return(v os.FileInfo, err error) *mock_osProvider_Stat_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *mock_osProvider_Stat_Call) RunAndReturn(run func(name string) (os.FileInfo, error)) *mock_osProvider_Stat_Call {
	_c.Call.Return(run)
	return _c
}
