// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Disk is an autogenerated mock type for the Disk type
type Disk struct {
	mock.Mock
}

type Disk_Expecter struct {
	mock *mock.Mock
}

func (_m *Disk) EXPECT() *Disk_Expecter {
	return &Disk_Expecter{mock: &_m.Mock}
}

// GetFSPath provides a mock function with no fields
func (_m *Disk) GetFSPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFSPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Disk_GetFSPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFSPath'
type Disk_GetFSPath_Call struct {
	*mock.Call
}

// GetFSPath is a helper method to define mock.On call
func (_e *Disk_Expecter) GetFSPath() *Disk_GetFSPath_Call {
	return &Disk_GetFSPath_Call{Call: _e.mock.On("GetFSPath")}
}

func (_c *Disk_GetFSPath_Call) Run(run func()) *Disk_GetFSPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Disk_GetFSPath_Call) Return(_a0 string) *Disk_GetFSPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Disk_GetFSPath_Call) RunAndReturn(run func() string) *Disk_GetFSPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with no fields
func (_m *Disk) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Disk_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type Disk_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *Disk_Expecter) GetName() *Disk_GetName_Call {
	return &Disk_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *Disk_GetName_Call) Run(run func()) *Disk_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Disk_GetName_Call) Return(_a0 string) *Disk_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Disk_GetName_Call) RunAndReturn(run func() string) *Disk_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// IsDisk provides a mock function with no fields
func (_m *Disk) IsDisk() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsDisk")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Disk_IsDisk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDisk'
type Disk_IsDisk_Call struct {
	*mock.Call
}

// IsDisk is a helper method to define mock.On call
func (_e *Disk_Expecter) IsDisk() *Disk_IsDisk_Call {
	return &Disk_IsDisk_Call{Call: _e.mock.On("IsDisk")}
}

func (_c *Disk_IsDisk_Call) Run(run func()) *Disk_IsDisk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Disk_IsDisk_Call) Return(_a0 bool) *Disk_IsDisk_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Disk_IsDisk_Call) RunAndReturn(run func() bool) *Disk_IsDisk_Call {
	_c.Call.Return(run)
	return _c
}

// NewDisk creates a new instance of Disk. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDisk(t interface {
	mock.TestingT
	Cleanup(func())
}) *Disk {
	mock := &Disk{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
