// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Pool is an autogenerated mock type for the Pool type
type Pool struct {
	mock.Mock
}

type Pool_Expecter struct {
	mock *mock.Mock
}

func (_m *Pool) EXPECT() *Pool_Expecter {
	return &Pool_Expecter{mock: &_m.Mock}
}

// GetFSPath provides a mock function with no fields
func (_m *Pool) GetFSPath() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFSPath")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Pool_GetFSPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFSPath'
type Pool_GetFSPath_Call struct {
	*mock.Call
}

// GetFSPath is a helper method to define mock.On call
func (_e *Pool_Expecter) GetFSPath() *Pool_GetFSPath_Call {
	return &Pool_GetFSPath_Call{Call: _e.mock.On("GetFSPath")}
}

func (_c *Pool_GetFSPath_Call) Run(run func()) *Pool_GetFSPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Pool_GetFSPath_Call) Return(_a0 string) *Pool_GetFSPath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Pool_GetFSPath_Call) RunAndReturn(run func() string) *Pool_GetFSPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with no fields
func (_m *Pool) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Pool_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type Pool_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *Pool_Expecter) GetName() *Pool_GetName_Call {
	return &Pool_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *Pool_GetName_Call) Run(run func()) *Pool_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Pool_GetName_Call) Return(_a0 string) *Pool_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Pool_GetName_Call) RunAndReturn(run func() string) *Pool_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// IsPool provides a mock function with no fields
func (_m *Pool) IsPool() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsPool")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Pool_IsPool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPool'
type Pool_IsPool_Call struct {
	*mock.Call
}

// IsPool is a helper method to define mock.On call
func (_e *Pool_Expecter) IsPool() *Pool_IsPool_Call {
	return &Pool_IsPool_Call{Call: _e.mock.On("IsPool")}
}

func (_c *Pool_IsPool_Call) Run(run func()) *Pool_IsPool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Pool_IsPool_Call) Return(_a0 bool) *Pool_IsPool_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Pool_IsPool_Call) RunAndReturn(run func() bool) *Pool_IsPool_Call {
	_c.Call.Return(run)
	return _c
}

// NewPool creates a new instance of Pool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *Pool {
	mock := &Pool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
