// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AllocProvider is an autogenerated mock type for the allocProvider type
type AllocProvider struct {
	mock.Mock
}

type AllocProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *AllocProvider) EXPECT() *AllocProvider_Expecter {
	return &AllocProvider_Expecter{mock: &_m.Mock}
}

// NewAllocProvider creates a new instance of AllocProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAllocProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *AllocProvider {
	mock := &AllocProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
