// Code generated by mockery. DO NOT EDIT.

package unraid

import mock "github.com/stretchr/testify/mock"

// mockFsProvider is an autogenerated mock type for the fsProvider type
type mockFsProvider struct {
	mock.Mock
}

type mockFsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockFsProvider) EXPECT() *mockFsProvider_Expecter {
	return &mockFsProvider_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function with given fields: path
func (_m *mockFsProvider) Exists(path string) (bool, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockFsProvider_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type mockFsProvider_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - path string
func (_e *mockFsProvider_Expecter) Exists(path interface{}) *mockFsProvider_Exists_Call {
	return &mockFsProvider_Exists_Call{Call: _e.mock.On("Exists", path)}
}

func (_c *mockFsProvider_Exists_Call) Run(run func(path string)) *mockFsProvider_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockFsProvider_Exists_Call) Return(_a0 bool, _a1 error) *mockFsProvider_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockFsProvider_Exists_Call) RunAndReturn(run func(string) (bool, error)) *mockFsProvider_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// newMockFsProvider creates a new instance of mockFsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockFsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockFsProvider {
	mock := &mockFsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
