// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package unraid

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// newMock_osProvider creates a new instance of mock_osProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMock_osProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mock_osProvider {
	mock := &mock_osProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mock_osProvider is an autogenerated mock type for the osProvider type
type mock_osProvider struct {
	mock.Mock
}

type mock_osProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mock_osProvider) EXPECT() *mock_osProvider_Expecter {
	return &mock_osProvider_Expecter{mock: &_m.Mock}
}

// ReadDir provides a mock function for the type mock_osProvider
func (_mock *mock_osProvider) ReadDir(name string) ([]os.DirEntry, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []os.DirEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]os.DirEntry, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []os.DirEntry); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]os.DirEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mock_osProvider_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type mock_osProvider_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - name string
func (_e *mock_osProvider_Expecter) ReadDir(name interface{}) *mock_osProvider_ReadDir_Call {
	return &mock_osProvider_ReadDir_Call{Call: _e.mock.On("ReadDir", name)}
}

func (_c *mock_osProvider_ReadDir_Call) Run(run func(name string)) *mock_osProvider_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mock_osProvider_ReadDir_Call) Return(vs []os.DirEntry, err error) *mock_osProvider_ReadDir_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *mock_osProvider_ReadDir_Call) RunAndReturn(run func(name string) ([]os.DirEntry, error)) *mock_osProvider_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// newMock_fsProvider creates a new instance of mock_fsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMock_fsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mock_fsProvider {
	mock := &mock_fsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mock_fsProvider is an autogenerated mock type for the fsProvider type
type mock_fsProvider struct {
	mock.Mock
}

type mock_fsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mock_fsProvider) EXPECT() *mock_fsProvider_Expecter {
	return &mock_fsProvider_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function for the type mock_fsProvider
func (_mock *mock_fsProvider) Exists(path string) (bool, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mock_fsProvider_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type mock_fsProvider_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - path string
func (_e *mock_fsProvider_Expecter) Exists(path interface{}) *mock_fsProvider_Exists_Call {
	return &mock_fsProvider_Exists_Call{Call: _e.mock.On("Exists", path)}
}

func (_c *mock_fsProvider_Exists_Call) Run(run func(path string)) *mock_fsProvider_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mock_fsProvider_Exists_Call) Return(b bool, err error) *mock_fsProvider_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mock_fsProvider_Exists_Call) RunAndReturn(run func(path string) (bool, error)) *mock_fsProvider_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// newMock_configProvider creates a new instance of mock_configProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMock_configProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mock_configProvider {
	mock := &mock_configProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mock_configProvider is an autogenerated mock type for the configProvider type
type mock_configProvider struct {
	mock.Mock
}

type mock_configProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mock_configProvider) EXPECT() *mock_configProvider_Expecter {
	return &mock_configProvider_Expecter{mock: &_m.Mock}
}

// MapKeyToInt provides a mock function for the type mock_configProvider
func (_mock *mock_configProvider) MapKeyToInt(envMap map[string]string, key string) int {
	ret := _mock.Called(envMap, key)

	if len(ret) == 0 {
		panic("no return value specified for MapKeyToInt")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(map[string]string, string) int); ok {
		r0 = returnFunc(envMap, key)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// mock_configProvider_MapKeyToInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapKeyToInt'
type mock_configProvider_MapKeyToInt_Call struct {
	*mock.Call
}

// MapKeyToInt is a helper method to define mock.On call
//   - envMap map[string]string
//   - key string
func (_e *mock_configProvider_Expecter) MapKeyToInt(envMap interface{}, key interface{}) *mock_configProvider_MapKeyToInt_Call {
	return &mock_configProvider_MapKeyToInt_Call{Call: _e.mock.On("MapKeyToInt", envMap, key)}
}

func (_c *mock_configProvider_MapKeyToInt_Call) Run(run func(envMap map[string]string, key string)) *mock_configProvider_MapKeyToInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]string
		if args[0] != nil {
			arg0 = args[0].(map[string]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mock_configProvider_MapKeyToInt_Call) Return(n int) *mock_configProvider_MapKeyToInt_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *mock_configProvider_MapKeyToInt_Call) RunAndReturn(run func(envMap map[string]string, key string) int) *mock_configProvider_MapKeyToInt_Call {
	_c.Call.Return(run)
	return _c
}

// MapKeyToInt64 provides a mock function for the type mock_configProvider
func (_mock *mock_configProvider) MapKeyToInt64(envMap map[string]string, key string) int64 {
	ret := _mock.Called(envMap, key)

	if len(ret) == 0 {
		panic("no return value specified for MapKeyToInt64")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func(map[string]string, string) int64); ok {
		r0 = returnFunc(envMap, key)
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// mock_configProvider_MapKeyToInt64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapKeyToInt64'
type mock_configProvider_MapKeyToInt64_Call struct {
	*mock.Call
}

// MapKeyToInt64 is a helper method to define mock.On call
//   - envMap map[string]string
//   - key string
func (_e *mock_configProvider_Expecter) MapKeyToInt64(envMap interface{}, key interface{}) *mock_configProvider_MapKeyToInt64_Call {
	return &mock_configProvider_MapKeyToInt64_Call{Call: _e.mock.On("MapKeyToInt64", envMap, key)}
}

func (_c *mock_configProvider_MapKeyToInt64_Call) Run(run func(envMap map[string]string, key string)) *mock_configProvider_MapKeyToInt64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]string
		if args[0] != nil {
			arg0 = args[0].(map[string]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mock_configProvider_MapKeyToInt64_Call) Return(n int64) *mock_configProvider_MapKeyToInt64_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *mock_configProvider_MapKeyToInt64_Call) RunAndReturn(run func(envMap map[string]string, key string) int64) *mock_configProvider_MapKeyToInt64_Call {
	_c.Call.Return(run)
	return _c
}

// MapKeyToString provides a mock function for the type mock_configProvider
func (_mock *mock_configProvider) MapKeyToString(envMap map[string]string, key string) string {
	ret := _mock.Called(envMap, key)

	if len(ret) == 0 {
		panic("no return value specified for MapKeyToString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(map[string]string, string) string); ok {
		r0 = returnFunc(envMap, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mock_configProvider_MapKeyToString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapKeyToString'
type mock_configProvider_MapKeyToString_Call struct {
	*mock.Call
}

// MapKeyToString is a helper method to define mock.On call
//   - envMap map[string]string
//   - key string
func (_e *mock_configProvider_Expecter) MapKeyToString(envMap interface{}, key interface{}) *mock_configProvider_MapKeyToString_Call {
	return &mock_configProvider_MapKeyToString_Call{Call: _e.mock.On("MapKeyToString", envMap, key)}
}

func (_c *mock_configProvider_MapKeyToString_Call) Run(run func(envMap map[string]string, key string)) *mock_configProvider_MapKeyToString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]string
		if args[0] != nil {
			arg0 = args[0].(map[string]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mock_configProvider_MapKeyToString_Call) Return(s string) *mock_configProvider_MapKeyToString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mock_configProvider_MapKeyToString_Call) RunAndReturn(run func(envMap map[string]string, key string) string) *mock_configProvider_MapKeyToString_Call {
	_c.Call.Return(run)
	return _c
}

// MapKeyToUInt64 provides a mock function for the type mock_configProvider
func (_mock *mock_configProvider) MapKeyToUInt64(envMap map[string]string, key string) uint64 {
	ret := _mock.Called(envMap, key)

	if len(ret) == 0 {
		panic("no return value specified for MapKeyToUInt64")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func(map[string]string, string) uint64); ok {
		r0 = returnFunc(envMap, key)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// mock_configProvider_MapKeyToUInt64_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapKeyToUInt64'
type mock_configProvider_MapKeyToUInt64_Call struct {
	*mock.Call
}

// MapKeyToUInt64 is a helper method to define mock.On call
//   - envMap map[string]string
//   - key string
func (_e *mock_configProvider_Expecter) MapKeyToUInt64(envMap interface{}, key interface{}) *mock_configProvider_MapKeyToUInt64_Call {
	return &mock_configProvider_MapKeyToUInt64_Call{Call: _e.mock.On("MapKeyToUInt64", envMap, key)}
}

func (_c *mock_configProvider_MapKeyToUInt64_Call) Run(run func(envMap map[string]string, key string)) *mock_configProvider_MapKeyToUInt64_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]string
		if args[0] != nil {
			arg0 = args[0].(map[string]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mock_configProvider_MapKeyToUInt64_Call) Return(v uint64) *mock_configProvider_MapKeyToUInt64_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *mock_configProvider_MapKeyToUInt64_Call) RunAndReturn(run func(envMap map[string]string, key string) uint64) *mock_configProvider_MapKeyToUInt64_Call {
	_c.Call.Return(run)
	return _c
}

// ReadGeneric provides a mock function for the type mock_configProvider
func (_mock *mock_configProvider) ReadGeneric(filenames ...string) (map[string]string, error) {
	// string
	_va := make([]interface{}, len(filenames))
	for _i := range filenames {
		_va[_i] = filenames[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ReadGeneric")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...string) (map[string]string, error)); ok {
		return returnFunc(filenames...)
	}
	if returnFunc, ok := ret.Get(0).(func(...string) map[string]string); ok {
		r0 = returnFunc(filenames...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...string) error); ok {
		r1 = returnFunc(filenames...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mock_configProvider_ReadGeneric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadGeneric'
type mock_configProvider_ReadGeneric_Call struct {
	*mock.Call
}

// ReadGeneric is a helper method to define mock.On call
//   - filenames ...string
func (_e *mock_configProvider_Expecter) ReadGeneric(filenames ...interface{}) *mock_configProvider_ReadGeneric_Call {
	return &mock_configProvider_ReadGeneric_Call{Call: _e.mock.On("ReadGeneric",
		append([]interface{}{}, filenames...)...)}
}

func (_c *mock_configProvider_ReadGeneric_Call) Run(run func(filenames ...string)) *mock_configProvider_ReadGeneric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *mock_configProvider_ReadGeneric_Call) Return(envMap map[string]string, err error) *mock_configProvider_ReadGeneric_Call {
	_c.Call.Return(envMap, err)
	return _c
}

func (_c *mock_configProvider_ReadGeneric_Call) RunAndReturn(run func(filenames ...string) (map[string]string, error)) *mock_configProvider_ReadGeneric_Call {
	_c.Call.Return(run)
	return _c
}
