// Code generated by mockery. DO NOT EDIT.

package unraid

import (
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// mockOsProvider is an autogenerated mock type for the osProvider type
type mockOsProvider struct {
	mock.Mock
}

type mockOsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOsProvider) EXPECT() *mockOsProvider_Expecter {
	return &mockOsProvider_Expecter{mock: &_m.Mock}
}

// ReadDir provides a mock function with given fields: name
func (_m *mockOsProvider) ReadDir(name string) ([]os.DirEntry, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []os.DirEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]os.DirEntry, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) []os.DirEntry); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]os.DirEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockOsProvider_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type mockOsProvider_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - name string
func (_e *mockOsProvider_Expecter) ReadDir(name interface{}) *mockOsProvider_ReadDir_Call {
	return &mockOsProvider_ReadDir_Call{Call: _e.mock.On("ReadDir", name)}
}

func (_c *mockOsProvider_ReadDir_Call) Run(run func(name string)) *mockOsProvider_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockOsProvider_ReadDir_Call) Return(_a0 []os.DirEntry, _a1 error) *mockOsProvider_ReadDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockOsProvider_ReadDir_Call) RunAndReturn(run func(string) ([]os.DirEntry, error)) *mockOsProvider_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// newMockOsProvider creates a new instance of mockOsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOsProvider {
	mock := &mockOsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
