# .github/workflows/go.yml
name: Linter (Go)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Call the reusable workflow to set up the environment
  setup:
    uses: ./.github/workflows/go-environment.yml

  # Lint job
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.setup.outputs.go-version }}
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
